/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AccountIndexRouteImport } from './routes/account/index'
import { Route as AccountResetPasswordRouteImport } from './routes/account/reset-password'
import { Route as AccountSignInRouteImport } from './routes/account/sign-in'
import { Route as AccountSignUpRouteImport } from './routes/account/sign-up'
import { Route as AccountUAccountIdRouteRouteImport } from './routes/account/u/$accountId/route'
import { Route as AccountUAccountIdIndexRouteImport } from './routes/account/u/$accountId/index'
import { Route as AccountUAccountIdAboutRouteImport } from './routes/account/u/$accountId/about'
import { Route as AccountUAccountIdAppsRouteImport } from './routes/account/u/$accountId/apps'
import { Route as AccountUAccountIdDevicesRouteImport } from './routes/account/u/$accountId/devices'
import { Route as AccountUAccountIdManageRouteImport } from './routes/account/u/$accountId/manage'

const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/account/',
  path: '/account/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountResetPasswordRoute = AccountResetPasswordRouteImport.update({
  id: '/account/reset-password',
  path: '/account/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountSignInRoute = AccountSignInRouteImport.update({
  id: '/account/sign-in',
  path: '/account/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountSignUpRoute = AccountSignUpRouteImport.update({
  id: '/account/sign-up',
  path: '/account/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountUAccountIdRouteRoute = AccountUAccountIdRouteRouteImport.update({
  id: '/account/u/$accountId',
  path: '/account/u/$accountId',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountUAccountIdIndexRoute = AccountUAccountIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AccountUAccountIdRouteRoute,
} as any)
const AccountUAccountIdAboutRoute = AccountUAccountIdAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => AccountUAccountIdRouteRoute,
} as any)
const AccountUAccountIdAppsRoute = AccountUAccountIdAppsRouteImport.update({
  id: '/apps',
  path: '/apps',
  getParentRoute: () => AccountUAccountIdRouteRoute,
} as any)
const AccountUAccountIdDevicesRoute =
  AccountUAccountIdDevicesRouteImport.update({
    id: '/devices',
    path: '/devices',
    getParentRoute: () => AccountUAccountIdRouteRoute,
  } as any)
const AccountUAccountIdManageRoute = AccountUAccountIdManageRouteImport.update({
  id: '/manage',
  path: '/manage',
  getParentRoute: () => AccountUAccountIdRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/account/reset-password': typeof AccountResetPasswordRoute
  '/account/sign-in': typeof AccountSignInRoute
  '/account/sign-up': typeof AccountSignUpRoute
  '/account/': typeof AccountIndexRoute
  '/account/u/$accountId': typeof AccountUAccountIdRouteRouteWithChildren
  '/account/u/$accountId/about': typeof AccountUAccountIdAboutRoute
  '/account/u/$accountId/apps': typeof AccountUAccountIdAppsRoute
  '/account/u/$accountId/devices': typeof AccountUAccountIdDevicesRoute
  '/account/u/$accountId/manage': typeof AccountUAccountIdManageRoute
  '/account/u/$accountId/': typeof AccountUAccountIdIndexRoute
}
export interface FileRoutesByTo {
  '/account/reset-password': typeof AccountResetPasswordRoute
  '/account/sign-in': typeof AccountSignInRoute
  '/account/sign-up': typeof AccountSignUpRoute
  '/account': typeof AccountIndexRoute
  '/account/u/$accountId/about': typeof AccountUAccountIdAboutRoute
  '/account/u/$accountId/apps': typeof AccountUAccountIdAppsRoute
  '/account/u/$accountId/devices': typeof AccountUAccountIdDevicesRoute
  '/account/u/$accountId/manage': typeof AccountUAccountIdManageRoute
  '/account/u/$accountId': typeof AccountUAccountIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/account/reset-password': typeof AccountResetPasswordRoute
  '/account/sign-in': typeof AccountSignInRoute
  '/account/sign-up': typeof AccountSignUpRoute
  '/account/': typeof AccountIndexRoute
  '/account/u/$accountId': typeof AccountUAccountIdRouteRouteWithChildren
  '/account/u/$accountId/about': typeof AccountUAccountIdAboutRoute
  '/account/u/$accountId/apps': typeof AccountUAccountIdAppsRoute
  '/account/u/$accountId/devices': typeof AccountUAccountIdDevicesRoute
  '/account/u/$accountId/manage': typeof AccountUAccountIdManageRoute
  '/account/u/$accountId/': typeof AccountUAccountIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/account/reset-password'
    | '/account/sign-in'
    | '/account/sign-up'
    | '/account/'
    | '/account/u/$accountId'
    | '/account/u/$accountId/about'
    | '/account/u/$accountId/apps'
    | '/account/u/$accountId/devices'
    | '/account/u/$accountId/manage'
    | '/account/u/$accountId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/account/reset-password'
    | '/account/sign-in'
    | '/account/sign-up'
    | '/account'
    | '/account/u/$accountId/about'
    | '/account/u/$accountId/apps'
    | '/account/u/$accountId/devices'
    | '/account/u/$accountId/manage'
    | '/account/u/$accountId'
  id:
    | '__root__'
    | '/account/reset-password'
    | '/account/sign-in'
    | '/account/sign-up'
    | '/account/'
    | '/account/u/$accountId'
    | '/account/u/$accountId/about'
    | '/account/u/$accountId/apps'
    | '/account/u/$accountId/devices'
    | '/account/u/$accountId/manage'
    | '/account/u/$accountId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AccountResetPasswordRoute: typeof AccountResetPasswordRoute
  AccountSignInRoute: typeof AccountSignInRoute
  AccountSignUpRoute: typeof AccountSignUpRoute
  AccountIndexRoute: typeof AccountIndexRoute
  AccountUAccountIdRouteRoute: typeof AccountUAccountIdRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/account/': {
      id: '/account/'
      path: '/account'
      fullPath: '/account/'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/reset-password': {
      id: '/account/reset-password'
      path: '/account/reset-password'
      fullPath: '/account/reset-password'
      preLoaderRoute: typeof AccountResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/sign-in': {
      id: '/account/sign-in'
      path: '/account/sign-in'
      fullPath: '/account/sign-in'
      preLoaderRoute: typeof AccountSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/sign-up': {
      id: '/account/sign-up'
      path: '/account/sign-up'
      fullPath: '/account/sign-up'
      preLoaderRoute: typeof AccountSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/u/$accountId': {
      id: '/account/u/$accountId'
      path: '/account/u/$accountId'
      fullPath: '/account/u/$accountId'
      preLoaderRoute: typeof AccountUAccountIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/u/$accountId/': {
      id: '/account/u/$accountId/'
      path: '/'
      fullPath: '/account/u/$accountId/'
      preLoaderRoute: typeof AccountUAccountIdIndexRouteImport
      parentRoute: typeof AccountUAccountIdRouteRoute
    }
    '/account/u/$accountId/about': {
      id: '/account/u/$accountId/about'
      path: '/about'
      fullPath: '/account/u/$accountId/about'
      preLoaderRoute: typeof AccountUAccountIdAboutRouteImport
      parentRoute: typeof AccountUAccountIdRouteRoute
    }
    '/account/u/$accountId/apps': {
      id: '/account/u/$accountId/apps'
      path: '/apps'
      fullPath: '/account/u/$accountId/apps'
      preLoaderRoute: typeof AccountUAccountIdAppsRouteImport
      parentRoute: typeof AccountUAccountIdRouteRoute
    }
    '/account/u/$accountId/devices': {
      id: '/account/u/$accountId/devices'
      path: '/devices'
      fullPath: '/account/u/$accountId/devices'
      preLoaderRoute: typeof AccountUAccountIdDevicesRouteImport
      parentRoute: typeof AccountUAccountIdRouteRoute
    }
    '/account/u/$accountId/manage': {
      id: '/account/u/$accountId/manage'
      path: '/manage'
      fullPath: '/account/u/$accountId/manage'
      preLoaderRoute: typeof AccountUAccountIdManageRouteImport
      parentRoute: typeof AccountUAccountIdRouteRoute
    }
  }
}

interface AccountUAccountIdRouteRouteChildren {
  AccountUAccountIdAboutRoute: typeof AccountUAccountIdAboutRoute
  AccountUAccountIdAppsRoute: typeof AccountUAccountIdAppsRoute
  AccountUAccountIdDevicesRoute: typeof AccountUAccountIdDevicesRoute
  AccountUAccountIdManageRoute: typeof AccountUAccountIdManageRoute
  AccountUAccountIdIndexRoute: typeof AccountUAccountIdIndexRoute
}

const AccountUAccountIdRouteRouteChildren: AccountUAccountIdRouteRouteChildren =
  {
    AccountUAccountIdAboutRoute: AccountUAccountIdAboutRoute,
    AccountUAccountIdAppsRoute: AccountUAccountIdAppsRoute,
    AccountUAccountIdDevicesRoute: AccountUAccountIdDevicesRoute,
    AccountUAccountIdManageRoute: AccountUAccountIdManageRoute,
    AccountUAccountIdIndexRoute: AccountUAccountIdIndexRoute,
  }

const AccountUAccountIdRouteRouteWithChildren =
  AccountUAccountIdRouteRoute._addFileChildren(
    AccountUAccountIdRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  AccountResetPasswordRoute: AccountResetPasswordRoute,
  AccountSignInRoute: AccountSignInRoute,
  AccountSignUpRoute: AccountSignUpRoute,
  AccountIndexRoute: AccountIndexRoute,
  AccountUAccountIdRouteRoute: AccountUAccountIdRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
