#!/usr/bin/env bash

# Extract the tail-end of the name of the script, e.g. "./pds-dev" -> "dev"
ENV="${0##*-}"
PDS_ENV="pds/${ENV}"
echo "Using ${PDS_ENV}"

# Login to vault, if needed
export VAULT_ADDR=https://vault.wsocial.cloud
vault token lookup >/dev/null 2>&1 || vault login -method=github -path=github

# Set up env vars
export PDS_ADMIN_PASSWORD="$(vault kv get -mount=secret -field ADMIN_PASSWORD $PDS_ENV)"
export PDS_HOST="https://$(vault kv get -mount=secret -field HOSTNAME $PDS_ENV)"
