packages:
  - 'services/*'
  - 'packages/*'
  - 'packages/lex/*'
  - 'packages/oauth/*'
  - 'packages/internal/*'

allowBuilds:
  '@bufbuild/buf': true
  '@swc/core': true
  better-sqlite3: true
  dd-trace: true
  esbuild: true
  protobufjs: true
  puppeteer: true
  sharp: true
  unrs-resolver: true
  '@datadog/native-appsec': false
  '@datadog/native-iast-taint-tracking': false
  '@datadog/native-metrics': false
  '@datadog/pprof': false
  core-js: false
  rolldown: true
  '@parcel/watcher': true

overrides:
  cookie: ^0.7.2
  opentelemetry-plugin-better-sqlite3>@opentelemetry/core: ^1.30.0
  'form-data@>=4.0.0 <4.0.4': '>=4.0.4'
  'fast-xml-parser@>=5.0.0 <5.3.5': '>=5.3.5'
  'protobufjs@<7.5.5': '>=7.5.5'
