// Root Error class
export { OAuthError } from './errors/oauth-error.js'

export { AccessDeniedError } from './errors/access-denied-error.js'
export { AccountSelectionRequiredError } from './errors/account-selection-required-error.js'
export { ConsentRequiredError } from './errors/consent-required-error.js'
export { InvalidAuthorizationDetailsError } from './errors/invalid-authorization-details-error.js'
export { InvalidClientError } from './errors/invalid-client-error.js'
export { InvalidClientMetadataError } from './errors/invalid-client-metadata-error.js'
export { InvalidDpopKeyBindingError } from './errors/invalid-dpop-key-binding.js'
export { InvalidDpopProofError } from './errors/invalid-dpop-proof-error.js'
export { InvalidParametersError } from './errors/invalid-parameters-error.js'
export { InvalidRedirectUriError } from './errors/invalid-redirect-uri-error.js'
export { InvalidRequestError } from './errors/invalid-request-error.js'
export { InvalidTokenError } from './errors/invalid-token-error.js'
export { LoginRequiredError } from './errors/login-required-error.js'
export { UnauthorizedClientError } from './errors/unauthorized-client-error.js'
export { UnauthorizedDpopError } from './errors/unauthorized-dpop-error.js'
export { UnauthorizedError } from './errors/unauthorized-error.js'
export { UnknownRequestError } from './errors/unknown-request-error.js'
export { UseDpopNonceError } from './errors/use-dpop-nonce-error.js'
