// @generated by protoc-gen-connect-es v1.3.0 with parameter "target=ts,import_extension="
// @generated from file bsync.proto (package bsync, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import {
  AddMuteOperationRequest,
  AddMuteOperationResponse,
  AddNotifOperationRequest,
  AddNotifOperationResponse,
  GetSubscriptionGroupRequest,
  GetSubscriptionGroupResponse,
  GetSubscriptionsRequest,
  GetSubscriptionsResponse,
  PingRequest,
  PingResponse,
  RefreshPurchasesRequest,
  RefreshPurchasesResponse,
  ScanMuteOperationsRequest,
  ScanMuteOperationsResponse,
  ScanNotifOperationsRequest,
  ScanNotifOperationsResponse,
  ScanPurchaseOperationsRequest,
  ScanPurchaseOperationsResponse,
} from './bsync_pb'
import { MethodKind } from '@bufbuild/protobuf'

/**
 * @generated from service bsync.Service
 */
export const Service = {
  typeName: 'bsync.Service',
  methods: {
    /**
     * Sync
     *
     * @generated from rpc bsync.Service.AddMuteOperation
     */
    addMuteOperation: {
      name: 'AddMuteOperation',
      I: AddMuteOperationRequest,
      O: AddMuteOperationResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc bsync.Service.ScanMuteOperations
     */
    scanMuteOperations: {
      name: 'ScanMuteOperations',
      I: ScanMuteOperationsRequest,
      O: ScanMuteOperationsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc bsync.Service.AddNotifOperation
     */
    addNotifOperation: {
      name: 'AddNotifOperation',
      I: AddNotifOperationRequest,
      O: AddNotifOperationResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc bsync.Service.ScanNotifOperations
     */
    scanNotifOperations: {
      name: 'ScanNotifOperations',
      I: ScanNotifOperationsRequest,
      O: ScanNotifOperationsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Purchase
     *
     * @generated from rpc bsync.Service.GetSubscriptions
     */
    getSubscriptions: {
      name: 'GetSubscriptions',
      I: GetSubscriptionsRequest,
      O: GetSubscriptionsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc bsync.Service.GetSubscriptionGroup
     */
    getSubscriptionGroup: {
      name: 'GetSubscriptionGroup',
      I: GetSubscriptionGroupRequest,
      O: GetSubscriptionGroupResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc bsync.Service.RefreshPurchases
     */
    refreshPurchases: {
      name: 'RefreshPurchases',
      I: RefreshPurchasesRequest,
      O: RefreshPurchasesResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc bsync.Service.ScanPurchaseOperations
     */
    scanPurchaseOperations: {
      name: 'ScanPurchaseOperations',
      I: ScanPurchaseOperationsRequest,
      O: ScanPurchaseOperationsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Ping
     *
     * @generated from rpc bsync.Service.Ping
     */
    ping: {
      name: 'Ping',
      I: PingRequest,
      O: PingResponse,
      kind: MethodKind.Unary,
    },
  },
} as const
