import * as url from 'url'
import { readFileSync, writeFileSync } from 'fs'
import { join } from 'path'
import * as prettier from 'prettier'

const __dirname = url.fileURLToPath(new URL('.', import.meta.url))

const labelsDef = JSON.parse(
  readFileSync(
    join(__dirname, '..', '..', 'definitions', 'labels.json'),
    'utf8',
  ),
)

writeFileSync(
  join(__dirname, '..', '..', 'src', 'moderation', 'const', 'label-groups.ts'),
  await gen(),
  'utf8',
)

async function gen() {
  return prettier.format(
    `/** this doc is generated by ./scripts/code/labels.mjs **/
  import {LabelGroupDefinition, LabelPreference} from '../types'
  import {LABELS} from './labels'

  export type LabelGroupId = ${labelsDef
    .map((group) => `"${group.id}"`)
    .join(' | ')}

  export const DEFAULT_LABEL_GROUP_SETTINGS: Record<string, LabelPreference> = ${JSON.stringify(
    Object.fromEntries(
      labelsDef
        .filter((group) => group.defaultSetting)
        .map((group) => [group.id, group.defaultSetting]),
    ),
  )}

  export const LABEL_GROUPS: Record<LabelGroupId, LabelGroupDefinition> = {
    ${genDefMap()}
  }
  `,
    { semi: false, parser: 'babel', singleQuote: true },
  )
}

function genDefMap() {
  const lines = []
  for (const group of labelsDef) {
    lines.push(`"${group.id}": {`)
    lines.push(`  id: "${group.id}",`)
    lines.push(`  configurable: ${group.configurable ? true : false},`)
    lines.push(
      `  labels: [${group.labels
        .map((label) => `LABELS["${label.id}"]`)
        .join(', ')}]`,
    )
    lines.push(`},`)
  }
  return lines.join('\n')
}

export {}
