/** this doc is generated by ./scripts/code/labels.mjs **/
import { LabelGroupDefinitionMap } from '../types'
import { LABELS } from './labels'

export const LABEL_GROUPS: LabelGroupDefinitionMap = {
  system: {
    id: 'system',
    configurable: false,
    labels: [
      LABELS['!hide'],
      LABELS['!no-promote'],
      LABELS['!warn'],
      LABELS['!no-unauthenticated'],
    ],
    strings: {
      settings: {
        en: {
          name: 'System',
          description: 'Moderator overrides for special cases.',
        },
      },
    },
  },
  legal: {
    id: 'legal',
    configurable: false,
    labels: [LABELS['dmca-violation'], LABELS['doxxing']],
    strings: {
      settings: {
        en: {
          name: 'Legal',
          description: 'Content removed for legal reasons.',
        },
      },
    },
  },
  'intellectual-property': {
    id: 'intellectual-property',
    configurable: true,
    labels: [LABELS['plagiarism']],
    strings: {
      settings: {
        en: {
          name: 'Intellectual Property',
          description: 'Plagiarism, copying without attribution.',
        },
      },
    },
  },
  porn: {
    id: 'porn',
    configurable: true,
    labels: [LABELS['porn']],
    strings: {
      settings: {
        en: {
          name: 'Explicit Sexual Images',
          description: 'i.e. pornography.',
        },
      },
    },
  },
  suggestive: {
    id: 'suggestive',
    configurable: true,
    labels: [LABELS['sexual']],
    strings: {
      settings: {
        en: {
          name: 'Sexually Suggestive',
          description: 'Does not include nudity.',
        },
      },
    },
  },
  nudity: {
    id: 'nudity',
    configurable: true,
    labels: [LABELS['nudity']],
    strings: {
      settings: {
        en: {
          name: 'Other Nudity',
          description: 'Including non-sexual and artistic.',
        },
      },
    },
  },
  violence: {
    id: 'violence',
    configurable: true,
    labels: [
      LABELS['nsfl'],
      LABELS['corpse'],
      LABELS['gore'],
      LABELS['torture'],
    ],
    strings: {
      settings: {
        en: {
          name: 'Violent / Bloody',
          description: 'Gore, self-harm, torture.',
        },
      },
    },
  },
  'drugs-alcohol': {
    id: 'drugs-alcohol',
    configurable: true,
    labels: [LABELS['substance-abuse']],
    strings: {
      settings: {
        en: {
          name: 'Substance Abuse',
          description: 'Use of drugs or alcohol.',
        },
      },
    },
  },
  'self-harm': {
    id: 'self-harm',
    configurable: true,
    labels: [LABELS['self-harm'], LABELS['eating-disorder']],
    strings: {
      settings: {
        en: {
          name: 'Self Harm',
          description: 'Suicide, self-harm, eating disorders.',
        },
      },
    },
  },
  intolerance: {
    id: 'intolerance',
    configurable: true,
    labels: [
      LABELS['intolerant-race'],
      LABELS['intolerant-gender'],
      LABELS['intolerant-sexual-orientation'],
      LABELS['intolerant-religion'],
      LABELS['intolerant'],
    ],
    strings: {
      settings: {
        en: {
          name: 'Intolerance',
          description:
            'Content or behavior which is hateful or intolerant toward a group of people.',
        },
      },
    },
  },
  'bad-behavior': {
    id: 'bad-behavior',
    configurable: true,
    labels: [LABELS['harassment'], LABELS['bullying'], LABELS['threat']],
    strings: {
      settings: {
        en: {
          name: 'Bad Behavior',
          description: 'Harassment, bullying, and threats toward other users.',
        },
      },
    },
  },
  rude: {
    id: 'rude',
    configurable: true,
    labels: [LABELS['rude']],
    strings: {
      settings: {
        en: {
          name: 'Rude',
          description: 'Behavior which is rude toward other users.',
        },
      },
    },
  },
  upsetting: {
    id: 'upsetting',
    configurable: true,
    labels: [LABELS['disgusting'], LABELS['upsetting']],
    strings: {
      settings: {
        en: {
          name: 'Upsetting',
          description: 'Shocking, disgusting, or generally upsetting content.',
        },
      },
    },
  },
  troubling: {
    id: 'troubling',
    configurable: true,
    labels: [LABELS['troubling'], LABELS['dispiriting'], LABELS['bad-news']],
    strings: {
      settings: {
        en: {
          name: 'Troubling',
          description:
            'Bad news, troubling information, or dispiriting content.',
        },
      },
    },
  },
  'hate-group-mention': {
    id: 'hate-group-mention',
    configurable: true,
    labels: [LABELS['icon-intolerant']],
    strings: {
      settings: {
        en: {
          name: 'Hate Group Coverage',
          description:
            'Images of terror groups, articles covering events, etc.',
        },
      },
    },
  },
  discourse: {
    id: 'discourse',
    configurable: true,
    labels: [LABELS['discourse'], LABELS['drama']],
    strings: {
      settings: {
        en: {
          name: 'Discourse / Drama',
          description:
            'On-going discussions or debates that may be frustrating.',
        },
      },
    },
  },
  curation: {
    id: 'curation',
    configurable: true,
    labels: [LABELS['curation']],
    strings: {
      settings: {
        en: {
          name: 'Curation',
          description:
            'Judgment of the moderators to remove content not worth showing.',
        },
      },
    },
  },
  spam: {
    id: 'spam',
    configurable: true,
    labels: [
      LABELS['spam'],
      LABELS['interaction-noise'],
      LABELS['engagement-farming'],
      LABELS['shilling'],
    ],
    strings: {
      settings: {
        en: {
          name: 'Spam',
          description: "Content which doesn't add to the conversation.",
        },
      },
    },
  },
  misrepresentation: {
    id: 'misrepresentation',
    configurable: true,
    labels: [LABELS['impersonation'], LABELS['scam']],
    strings: {
      settings: {
        en: { name: 'Security', description: 'Impersonations, scams.' },
      },
    },
  },
  security: {
    id: 'security',
    configurable: true,
    labels: [LABELS['account-security'], LABELS['net-abuse']],
    strings: {
      settings: {
        en: { name: 'Security', description: 'Potential security attacks.' },
      },
    },
  },
  misinfo: {
    id: 'misinfo',
    configurable: true,
    labels: [
      LABELS['misinfo'],
      LABELS['misleading'],
      LABELS['unverified'],
      LABELS['manipulated'],
      LABELS['fringe'],
    ],
    strings: {
      settings: {
        en: {
          name: 'Misinformation',
          description: 'Content which misleads or defrauds users.',
        },
      },
    },
  },
  context: {
    id: 'context',
    configurable: false,
    labels: [
      LABELS['satire'],
      LABELS['parody'],
      LABELS['bot'],
      LABELS['ai-generated'],
    ],
    strings: {
      settings: {
        en: {
          name: 'Context',
          description:
            'Helpful annotations to explain intent, such as satire or parody.',
        },
      },
    },
  },
}
