/** this doc is generated by ./scripts/code/labels.mjs **/
import { LabelDefinition } from '../types'

export type KnownLabelValue =
  | '!hide'
  | '!no-promote'
  | '!warn'
  | '!no-unauthenticated'
  | 'dmca-violation'
  | 'doxxing'
  | 'plagiarism'
  | 'porn'
  | 'sexual'
  | 'nudity'
  | 'nsfl'
  | 'corpse'
  | 'gore'
  | 'torture'
  | 'substance-abuse'
  | 'self-harm'
  | 'eating-disorder'
  | 'intolerant-race'
  | 'intolerant-gender'
  | 'intolerant-sexual-orientation'
  | 'intolerant-religion'
  | 'intolerant'
  | 'harassment'
  | 'bullying'
  | 'threat'
  | 'rude'
  | 'disgusting'
  | 'upsetting'
  | 'troubling'
  | 'dispiriting'
  | 'bad-news'
  | 'icon-intolerant'
  | 'discourse'
  | 'drama'
  | 'dislike'
  | 'spam'
  | 'interaction-noise'
  | 'engagement-farming'
  | 'shilling'
  | 'impersonation'
  | 'scam'
  | 'account-security'
  | 'net-abuse'
  | 'misinfo'
  | 'misleading'
  | 'unverified'
  | 'manipulated'
  | 'fringe'
  | 'satire'
  | 'parody'
  | 'bot'
  | 'ai-generated'

export const LABELS: Record<KnownLabelValue, LabelDefinition> = {
  '!hide': {
    id: '!hide',
    targets: ['account', 'profile', 'content'],
    fixedPreference: 'hide',
    flags: ['no-override', 'no-self'],
    behaviors: {
      account: {
        profileList: 'blur',
        profileView: 'blur',
        avatar: 'blur',
        banner: 'blur',
        displayName: 'blur',
        contentList: 'blur',
        contentView: 'blur',
      },
      profile: {
        avatar: 'blur',
        banner: 'blur',
        displayName: 'blur',
      },
      content: {
        contentList: 'blur',
        contentView: 'blur',
      },
    },
    groupId: 'system',
    configurable: false,
  },
  '!no-promote': {
    id: '!no-promote',
    targets: ['account', 'content'],
    fixedPreference: 'hide',
    flags: ['no-self'],
    behaviors: {},
    groupId: 'system',
    configurable: false,
  },
  '!warn': {
    id: '!warn',
    targets: ['account', 'profile', 'content'],
    fixedPreference: 'warn',
    flags: ['no-self'],
    behaviors: {
      account: {
        profileList: 'blur',
        profileView: 'blur',
        avatar: 'blur',
        banner: 'blur',
        contentList: 'blur',
        contentView: 'blur',
      },
      profile: {
        avatar: 'blur',
        banner: 'blur',
        displayName: 'blur',
      },
      content: {
        contentList: 'blur',
        contentView: 'blur',
      },
    },
    groupId: 'system',
    configurable: false,
  },
  '!no-unauthenticated': {
    id: '!no-unauthenticated',
    targets: ['account', 'profile', 'content'],
    fixedPreference: 'hide',
    flags: ['no-override', 'unauthed'],
    behaviors: {
      account: {
        profileList: 'blur',
        profileView: 'blur',
        avatar: 'blur',
        banner: 'blur',
        displayName: 'blur',
        contentList: 'blur',
        contentView: 'blur',
      },
      profile: {
        avatar: 'blur',
        banner: 'blur',
        displayName: 'blur',
      },
      content: {
        contentList: 'blur',
        contentView: 'blur',
      },
    },
    groupId: 'system',
    configurable: false,
  },
  'dmca-violation': {
    id: 'dmca-violation',
    targets: ['content'],
    fixedPreference: 'hide',
    flags: ['no-override', 'no-self'],
    behaviors: {
      content: {
        contentList: 'blur',
        contentView: 'blur',
      },
    },
    groupId: 'legal',
    configurable: false,
  },
  doxxing: {
    id: 'doxxing',
    targets: ['account', 'content'],
    fixedPreference: 'hide',
    flags: ['no-override', 'no-self'],
    behaviors: {
      account: {
        profileList: 'blur',
        profileView: 'blur',
        contentList: 'blur',
        contentView: 'blur',
      },
      content: {
        contentList: 'blur',
        contentView: 'blur',
      },
    },
    groupId: 'legal',
    configurable: false,
  },
  plagiarism: {
    id: 'plagiarism',
    targets: ['content'],
    flags: ['no-self'],
    behaviors: {
      content: {
        contentList: 'inform',
        contentView: 'inform',
      },
    },
    groupId: 'intellectual-property',
    configurable: true,
  },
  porn: {
    id: 'porn',
    targets: ['profile', 'content'],
    flags: ['adult'],
    behaviors: {
      profile: {
        avatar: 'blur',
        banner: 'blur',
      },
      content: {
        contentMedia: 'blur',
      },
    },
    groupId: 'porn',
    configurable: true,
  },
  sexual: {
    id: 'sexual',
    targets: ['profile', 'content'],
    flags: ['adult'],
    behaviors: {
      profile: {
        avatar: 'blur',
        banner: 'blur',
      },
      content: {
        contentMedia: 'blur',
      },
    },
    groupId: 'suggestive',
    configurable: true,
  },
  nudity: {
    id: 'nudity',
    targets: ['profile', 'content'],
    flags: ['adult'],
    behaviors: {
      profile: {
        avatar: 'blur',
        banner: 'blur',
      },
      content: {
        contentMedia: 'blur',
      },
    },
    groupId: 'nudity',
    configurable: true,
  },
  nsfl: {
    id: 'nsfl',
    targets: ['profile', 'content'],
    flags: ['adult'],
    behaviors: {
      profile: {
        avatar: 'blur',
        banner: 'blur',
      },
      content: {
        contentMedia: 'blur',
      },
    },
    groupId: 'violence',
    configurable: true,
  },
  corpse: {
    id: 'corpse',
    targets: ['profile', 'content'],
    flags: ['adult'],
    behaviors: {
      profile: {
        avatar: 'blur',
        banner: 'blur',
      },
      content: {
        contentMedia: 'blur',
      },
    },
    groupId: 'violence',
    configurable: true,
  },
  gore: {
    id: 'gore',
    targets: ['profile', 'content'],
    flags: ['adult'],
    behaviors: {
      profile: {
        avatar: 'blur',
        banner: 'blur',
      },
      content: {
        contentMedia: 'blur',
      },
    },
    groupId: 'violence',
    configurable: true,
  },
  torture: {
    id: 'torture',
    targets: ['profile', 'content'],
    flags: ['adult'],
    behaviors: {
      profile: {
        avatar: 'blur',
        banner: 'blur',
      },
      content: {
        contentMedia: 'blur',
      },
    },
    groupId: 'violence',
    configurable: true,
  },
  'substance-abuse': {
    id: 'substance-abuse',
    targets: ['profile', 'content'],
    flags: [],
    behaviors: {
      profile: {
        avatar: 'blur',
        banner: 'blur',
      },
      content: {
        contentMedia: 'blur',
      },
    },
    groupId: 'drugs-alcohol',
    configurable: true,
  },
  'self-harm': {
    id: 'self-harm',
    targets: ['profile', 'content'],
    flags: [],
    behaviors: {
      profile: {
        avatar: 'blur',
        banner: 'blur',
      },
      content: {
        contentList: 'blur',
        contentView: 'blur',
      },
    },
    groupId: 'self-harm',
    configurable: true,
  },
  'eating-disorder': {
    id: 'eating-disorder',
    targets: ['profile', 'content'],
    flags: [],
    behaviors: {
      profile: {
        avatar: 'blur',
        banner: 'blur',
      },
      content: {
        contentList: 'blur',
        contentView: 'blur',
      },
    },
    groupId: 'self-harm',
    configurable: true,
  },
  'intolerant-race': {
    id: 'intolerant-race',
    targets: ['account', 'profile', 'content'],
    flags: ['no-self'],
    behaviors: {
      account: {
        profileList: 'alert',
        profileView: 'alert',
        contentList: 'blur',
        contentView: 'alert',
      },
      profile: {
        avatar: 'blur',
        banner: 'blur',
        displayName: 'blur',
      },
      content: {
        contentList: 'blur',
        contentView: 'alert',
      },
    },
    groupId: 'intolerance',
    configurable: true,
  },
  'intolerant-gender': {
    id: 'intolerant-gender',
    targets: ['account', 'profile', 'content'],
    flags: ['no-self'],
    behaviors: {
      account: {
        profileList: 'alert',
        profileView: 'alert',
        contentList: 'blur',
        contentView: 'alert',
      },
      profile: {
        avatar: 'blur',
        banner: 'blur',
        displayName: 'blur',
      },
      content: {
        contentList: 'blur',
        contentView: 'alert',
      },
    },
    groupId: 'intolerance',
    configurable: true,
  },
  'intolerant-sexual-orientation': {
    id: 'intolerant-sexual-orientation',
    targets: ['account', 'profile', 'content'],
    flags: ['no-self'],
    behaviors: {
      account: {
        profileList: 'alert',
        profileView: 'alert',
        contentList: 'blur',
        contentView: 'alert',
      },
      profile: {
        avatar: 'blur',
        banner: 'blur',
        displayName: 'blur',
      },
      content: {
        contentList: 'blur',
        contentView: 'alert',
      },
    },
    groupId: 'intolerance',
    configurable: true,
  },
  'intolerant-religion': {
    id: 'intolerant-religion',
    targets: ['account', 'profile', 'content'],
    flags: ['no-self'],
    behaviors: {
      account: {
        profileList: 'alert',
        profileView: 'alert',
        contentList: 'blur',
        contentView: 'alert',
      },
      profile: {
        avatar: 'blur',
        banner: 'blur',
        displayName: 'blur',
      },
      content: {
        contentList: 'blur',
        contentView: 'alert',
      },
    },
    groupId: 'intolerance',
    configurable: true,
  },
  intolerant: {
    id: 'intolerant',
    targets: ['account', 'profile', 'content'],
    flags: ['no-self'],
    behaviors: {
      account: {
        profileList: 'alert',
        profileView: 'alert',
        contentList: 'blur',
        contentView: 'alert',
      },
      profile: {
        avatar: 'blur',
        banner: 'blur',
        displayName: 'blur',
      },
      content: {
        contentList: 'blur',
        contentView: 'alert',
      },
    },
    groupId: 'intolerance',
    configurable: true,
  },
  harassment: {
    id: 'harassment',
    targets: ['account', 'content'],
    flags: ['no-self'],
    behaviors: {
      account: {
        profileList: 'alert',
        profileView: 'alert',
        contentList: 'blur',
        contentView: 'alert',
      },
      content: {
        contentList: 'blur',
        contentView: 'alert',
      },
    },
    groupId: 'bad-behavior',
    configurable: true,
  },
  bullying: {
    id: 'bullying',
    targets: ['account', 'content'],
    flags: ['no-self'],
    behaviors: {
      account: {
        profileList: 'alert',
        profileView: 'alert',
        contentList: 'blur',
        contentView: 'alert',
      },
      content: {
        contentList: 'blur',
        contentView: 'alert',
      },
    },
    groupId: 'bad-behavior',
    configurable: true,
  },
  threat: {
    id: 'threat',
    targets: ['account', 'content'],
    flags: ['no-self'],
    behaviors: {
      account: {
        profileList: 'alert',
        profileView: 'alert',
        contentList: 'blur',
        contentView: 'alert',
      },
      content: {
        contentList: 'blur',
        contentView: 'alert',
      },
    },
    groupId: 'bad-behavior',
    configurable: true,
  },
  rude: {
    id: 'rude',
    targets: ['account', 'content'],
    flags: ['no-self'],
    behaviors: {
      account: {
        profileList: 'alert',
        profileView: 'alert',
        contentList: 'blur',
        contentView: 'alert',
      },
      content: {
        contentList: 'blur',
        contentView: 'alert',
      },
    },
    groupId: 'rude',
    configurable: true,
  },
  disgusting: {
    id: 'disgusting',
    targets: ['profile', 'content'],
    flags: [],
    behaviors: {
      profile: {
        avatar: 'blur',
        banner: 'blur',
      },
      content: {
        contentMedia: 'blur',
      },
    },
    groupId: 'upsetting',
    configurable: true,
  },
  upsetting: {
    id: 'upsetting',
    targets: ['profile', 'content'],
    flags: [],
    behaviors: {
      profile: {
        avatar: 'blur',
        banner: 'blur',
      },
      content: {
        contentMedia: 'blur',
      },
    },
    groupId: 'upsetting',
    configurable: true,
  },
  troubling: {
    id: 'troubling',
    targets: ['content'],
    flags: [],
    behaviors: {
      content: {
        contentList: 'blur',
        contentView: 'blur',
      },
    },
    groupId: 'troubling',
    configurable: true,
  },
  dispiriting: {
    id: 'dispiriting',
    targets: ['content'],
    flags: [],
    behaviors: {
      content: {
        contentList: 'blur',
        contentView: 'blur',
      },
    },
    groupId: 'troubling',
    configurable: true,
  },
  'bad-news': {
    id: 'bad-news',
    targets: ['content'],
    flags: [],
    behaviors: {
      content: {
        contentList: 'blur',
        contentView: 'blur',
      },
    },
    groupId: 'troubling',
    configurable: true,
  },
  'icon-intolerant': {
    id: 'icon-intolerant',
    targets: ['profile', 'content'],
    flags: [],
    behaviors: {
      profile: {
        avatar: 'blur',
        banner: 'blur',
      },
      content: {
        contentMedia: 'blur',
      },
    },
    groupId: 'hate-group-mention',
    configurable: true,
  },
  discourse: {
    id: 'discourse',
    targets: ['content'],
    flags: [],
    behaviors: {
      content: {
        contentList: 'blur',
        contentView: 'inform',
      },
    },
    groupId: 'discourse',
    configurable: true,
  },
  drama: {
    id: 'drama',
    targets: ['content'],
    flags: [],
    behaviors: {
      content: {
        contentList: 'blur',
        contentView: 'inform',
      },
    },
    groupId: 'discourse',
    configurable: true,
  },
  dislike: {
    id: 'dislike',
    targets: ['account', 'content'],
    flags: ['no-self'],
    behaviors: {
      account: {
        profileList: 'inform',
        profileView: 'inform',
        contentList: 'blur',
        contentView: 'inform',
      },
      content: {
        contentList: 'blur',
        contentView: 'inform',
      },
    },
    groupId: 'curation',
    configurable: true,
  },
  spam: {
    id: 'spam',
    targets: ['account', 'content'],
    flags: ['no-self'],
    behaviors: {
      account: {
        profileList: 'inform',
        profileView: 'inform',
        contentList: 'blur',
        contentView: 'inform',
      },
      content: {
        contentList: 'blur',
        contentView: 'inform',
      },
    },
    groupId: 'spam',
    configurable: true,
  },
  'interaction-noise': {
    id: 'interaction-noise',
    targets: ['account', 'content'],
    flags: ['no-self'],
    behaviors: {
      account: {
        profileList: 'inform',
        profileView: 'inform',
        contentList: 'blur',
        contentView: 'inform',
      },
      content: {
        contentList: 'blur',
        contentView: 'inform',
      },
    },
    groupId: 'spam',
    configurable: true,
  },
  'engagement-farming': {
    id: 'engagement-farming',
    targets: ['account', 'content'],
    flags: ['no-self'],
    behaviors: {
      account: {
        profileList: 'inform',
        profileView: 'inform',
        contentList: 'blur',
        contentView: 'inform',
      },
      content: {
        contentList: 'blur',
        contentView: 'inform',
      },
    },
    groupId: 'spam',
    configurable: true,
  },
  shilling: {
    id: 'shilling',
    targets: ['account', 'content'],
    flags: ['no-self'],
    behaviors: {
      account: {
        profileList: 'inform',
        profileView: 'inform',
        contentList: 'blur',
        contentView: 'inform',
      },
      content: {
        contentList: 'blur',
        contentView: 'inform',
      },
    },
    groupId: 'spam',
    configurable: true,
  },
  impersonation: {
    id: 'impersonation',
    targets: ['account'],
    flags: ['no-self'],
    behaviors: {
      account: {
        profileList: 'alert',
        profileView: 'alert',
        contentList: 'alert',
        contentView: 'alert',
      },
    },
    groupId: 'misrepresentation',
    configurable: true,
  },
  scam: {
    id: 'scam',
    targets: ['account', 'content'],
    flags: ['no-self'],
    behaviors: {
      account: {
        profileList: 'alert',
        profileView: 'alert',
        avatar: 'alert',
        contentList: 'blur',
        contentView: 'alert',
      },
      content: {
        contentList: 'blur',
        contentView: 'alert',
      },
    },
    groupId: 'misrepresentation',
    configurable: true,
  },
  'account-security': {
    id: 'account-security',
    targets: ['account', 'content'],
    flags: ['no-self'],
    behaviors: {
      account: {
        profileList: 'alert',
        profileView: 'alert',
        avatar: 'alert',
        contentList: 'blur',
        contentView: 'alert',
      },
      content: {
        contentList: 'blur',
        contentView: 'alert',
      },
    },
    groupId: 'security',
    configurable: true,
  },
  'net-abuse': {
    id: 'net-abuse',
    targets: ['account', 'content'],
    flags: ['no-self'],
    behaviors: {
      account: {
        profileList: 'alert',
        profileView: 'alert',
        avatar: 'alert',
        contentList: 'blur',
        contentView: 'alert',
      },
      content: {
        contentList: 'blur',
        contentView: 'alert',
      },
    },
    groupId: 'security',
    configurable: true,
  },
  misinfo: {
    id: 'misinfo',
    targets: ['profile', 'content'],
    flags: ['no-self'],
    behaviors: {
      profile: {
        profileList: 'inform',
        profileView: 'inform',
      },
      content: {
        contentList: 'blur',
        contentView: 'inform',
      },
    },
    groupId: 'misinfo',
    configurable: true,
  },
  misleading: {
    id: 'misleading',
    targets: ['profile', 'content'],
    flags: ['no-self'],
    behaviors: {
      profile: {
        profileList: 'inform',
        profileView: 'inform',
      },
      content: {
        contentList: 'blur',
        contentView: 'inform',
      },
    },
    groupId: 'misinfo',
    configurable: true,
  },
  unverified: {
    id: 'unverified',
    targets: ['profile', 'content'],
    flags: [],
    behaviors: {
      profile: {
        profileList: 'inform',
        profileView: 'inform',
      },
      content: {
        contentList: 'blur',
        contentView: 'inform',
      },
    },
    groupId: 'misinfo',
    configurable: true,
  },
  manipulated: {
    id: 'manipulated',
    targets: ['profile', 'content'],
    flags: ['no-self'],
    behaviors: {
      profile: {
        profileList: 'inform',
        profileView: 'inform',
      },
      content: {
        contentList: 'blur',
        contentView: 'inform',
      },
    },
    groupId: 'misinfo',
    configurable: true,
  },
  fringe: {
    id: 'fringe',
    targets: ['profile', 'content'],
    flags: ['no-self'],
    behaviors: {
      profile: {
        profileList: 'inform',
        profileView: 'inform',
      },
      content: {
        contentList: 'blur',
        contentView: 'inform',
      },
    },
    groupId: 'misinfo',
    configurable: true,
  },
  satire: {
    id: 'satire',
    targets: ['account', 'content'],
    fixedPreference: 'warn',
    flags: [],
    behaviors: {
      account: {
        profileList: 'inform',
        profileView: 'inform',
        contentList: 'inform',
        contentView: 'inform',
      },
      content: {
        contentList: 'inform',
        contentView: 'inform',
      },
    },
    groupId: 'context',
    configurable: false,
  },
  parody: {
    id: 'parody',
    targets: ['account', 'content'],
    fixedPreference: 'warn',
    flags: [],
    behaviors: {
      account: {
        profileList: 'inform',
        profileView: 'inform',
        contentList: 'inform',
        contentView: 'inform',
      },
      content: {
        contentList: 'inform',
        contentView: 'inform',
      },
    },
    groupId: 'context',
    configurable: false,
  },
  bot: {
    id: 'bot',
    targets: ['account'],
    flags: [],
    behaviors: {
      account: {
        profileList: 'inform',
        profileView: 'inform',
        contentList: 'inform',
        contentView: 'inform',
      },
      content: {
        contentList: 'inform',
        contentView: 'inform',
      },
    },
    groupId: 'context',
    configurable: false,
  },
  'ai-generated': {
    id: 'ai-generated',
    targets: ['account', 'profile', 'content'],
    flags: [],
    behaviors: {
      account: {
        profileList: 'inform',
        profileView: 'inform',
        contentList: 'inform',
        contentView: 'inform',
      },
      profile: {
        profileList: 'inform',
        profileView: 'inform',
      },
      content: {
        contentList: 'inform',
        contentView: 'inform',
      },
    },
    groupId: 'context',
    configurable: false,
  },
}
