/** this doc is generated by ./scripts/code/labels.mjs **/
import { LabelGroupDefinition, LabelPreference } from '../types'
import { LABELS } from './labels'

export type LabelGroupId =
  | 'system'
  | 'legal'
  | 'intellectual-property'
  | 'porn'
  | 'suggestive'
  | 'nudity'
  | 'violence'
  | 'drugs-alcohol'
  | 'self-harm'
  | 'intolerance'
  | 'bad-behavior'
  | 'rude'
  | 'upsetting'
  | 'troubling'
  | 'hate-group-mention'
  | 'discourse'
  | 'curation'
  | 'spam'
  | 'misrepresentation'
  | 'security'
  | 'misinfo'
  | 'context'

export const DEFAULT_LABEL_GROUP_SETTINGS: Record<string, LabelPreference> = {
  'intellectual-property': 'warn',
  porn: 'hide',
  suggestive: 'warn',
  nudity: 'warn',
  violence: 'warn',
  'drugs-alcohol': 'ignore',
  'self-harm': 'warn',
  intolerance: 'hide',
  'bad-behavior': 'ignore',
  rude: 'ignore',
  upsetting: 'ignore',
  troubling: 'ignore',
  'hate-group-mention': 'ignore',
  discourse: 'ignore',
  curation: 'ignore',
  spam: 'hide',
  misrepresentation: 'warn',
  security: 'warn',
  misinfo: 'warn',
}

export const LABEL_GROUPS: Record<LabelGroupId, LabelGroupDefinition> = {
  system: {
    id: 'system',
    configurable: false,
    labels: [
      LABELS['!hide'],
      LABELS['!no-promote'],
      LABELS['!warn'],
      LABELS['!no-unauthenticated'],
    ],
  },
  legal: {
    id: 'legal',
    configurable: false,
    labels: [LABELS['dmca-violation'], LABELS['doxxing']],
  },
  'intellectual-property': {
    id: 'intellectual-property',
    configurable: true,
    labels: [LABELS['plagiarism']],
  },
  porn: {
    id: 'porn',
    configurable: true,
    labels: [LABELS['porn']],
  },
  suggestive: {
    id: 'suggestive',
    configurable: true,
    labels: [LABELS['sexual']],
  },
  nudity: {
    id: 'nudity',
    configurable: true,
    labels: [LABELS['nudity']],
  },
  violence: {
    id: 'violence',
    configurable: true,
    labels: [
      LABELS['nsfl'],
      LABELS['corpse'],
      LABELS['gore'],
      LABELS['torture'],
    ],
  },
  'drugs-alcohol': {
    id: 'drugs-alcohol',
    configurable: true,
    labels: [LABELS['substance-abuse']],
  },
  'self-harm': {
    id: 'self-harm',
    configurable: true,
    labels: [LABELS['self-harm'], LABELS['eating-disorder']],
  },
  intolerance: {
    id: 'intolerance',
    configurable: true,
    labels: [
      LABELS['intolerant-race'],
      LABELS['intolerant-gender'],
      LABELS['intolerant-sexual-orientation'],
      LABELS['intolerant-religion'],
      LABELS['intolerant'],
    ],
  },
  'bad-behavior': {
    id: 'bad-behavior',
    configurable: true,
    labels: [LABELS['harassment'], LABELS['bullying'], LABELS['threat']],
  },
  rude: {
    id: 'rude',
    configurable: true,
    labels: [LABELS['rude']],
  },
  upsetting: {
    id: 'upsetting',
    configurable: true,
    labels: [LABELS['disgusting'], LABELS['upsetting']],
  },
  troubling: {
    id: 'troubling',
    configurable: true,
    labels: [LABELS['troubling'], LABELS['dispiriting'], LABELS['bad-news']],
  },
  'hate-group-mention': {
    id: 'hate-group-mention',
    configurable: true,
    labels: [LABELS['icon-intolerant']],
  },
  discourse: {
    id: 'discourse',
    configurable: true,
    labels: [LABELS['discourse'], LABELS['drama']],
  },
  curation: {
    id: 'curation',
    configurable: true,
    labels: [LABELS['dislike']],
  },
  spam: {
    id: 'spam',
    configurable: true,
    labels: [
      LABELS['spam'],
      LABELS['interaction-noise'],
      LABELS['engagement-farming'],
      LABELS['shilling'],
    ],
  },
  misrepresentation: {
    id: 'misrepresentation',
    configurable: true,
    labels: [LABELS['impersonation'], LABELS['scam']],
  },
  security: {
    id: 'security',
    configurable: true,
    labels: [LABELS['account-security'], LABELS['net-abuse']],
  },
  misinfo: {
    id: 'misinfo',
    configurable: true,
    labels: [
      LABELS['misinfo'],
      LABELS['misleading'],
      LABELS['unverified'],
      LABELS['manipulated'],
      LABELS['fringe'],
    ],
  },
  context: {
    id: 'context',
    configurable: false,
    labels: [
      LABELS['satire'],
      LABELS['parody'],
      LABELS['bot'],
      LABELS['ai-generated'],
    ],
  },
}
