import { Options as PrettierOptions, format as prettierFormat } from 'prettier'

const DEFAULT_FORMAT_OPTIONS: PrettierOptions = {
  parser: 'typescript',
  tabWidth: 2,
  semi: false,
  singleQuote: true,
  trailingComma: 'all',
}

const DEFAULT_BANNER = `/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */`

export type FormatterOptions = {
  /** @default false */
  pretty?: boolean | PrettierOptions
  banner?: string
}

export class Formatter {
  readonly banner: string
  readonly prettierOptions: PrettierOptions | null

  constructor(options: FormatterOptions = {}) {
    this.banner = options?.banner ?? DEFAULT_BANNER

    this.prettierOptions =
      options?.pretty === true
        ? DEFAULT_FORMAT_OPTIONS
        : options?.pretty || null
  }

  async format(code: string) {
    const bannerPadding =
      this.banner && !this.banner.endsWith('\n') ? '\n\n' : ''
    const codePretty = this.prettierOptions
      ? await prettierFormat(code, this.prettierOptions)
      : code
    return `${this.banner}${bannerPadding}${codePretty}`
  }
}
