import { Options as PrettierOptions, format as prettierFormat } from 'prettier'

const DEFAULT_FORMAT_OPTIONS: PrettierOptions = {
  parser: 'typescript',
  tabWidth: 2,
  semi: false,
  singleQuote: true,
  trailingComma: 'all',
}

const DEFAULT_BANNER = `/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */`

/**
 * Options for configuring the code formatter.
 */
export type FormatterOptions = {
  /**
   * Whether to format the generated code with Prettier.
   *
   * - `false`: No formatting (default)
   * - `true`: Format with default Prettier options
   * - `PrettierOptions`: Format with custom Prettier configuration
   *
   * @default false
   */
  pretty?: boolean | PrettierOptions
  /**
   * A banner comment to prepend to each generated file.
   *
   * @default '/* THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT. *\/'
   */
  banner?: string
}

/**
 * Formats generated TypeScript code with optional Prettier formatting
 * and banner comments.
 *
 * @example
 * ```ts
 * const formatter = new Formatter({ pretty: true })
 * const formatted = await formatter.format(generatedCode)
 * ```
 */
export class Formatter {
  /** The banner comment to prepend to formatted code. */
  readonly banner: string
  /** Prettier options, or `null` if formatting is disabled. */
  readonly prettierOptions: PrettierOptions | null

  /**
   * Creates a new Formatter instance.
   *
   * @param options - Formatting configuration options
   */
  constructor(options: FormatterOptions = {}) {
    this.banner = options?.banner ?? DEFAULT_BANNER

    this.prettierOptions =
      options?.pretty === true
        ? DEFAULT_FORMAT_OPTIONS
        : options?.pretty || null
  }

  /**
   * Formats the given code string.
   *
   * Applies Prettier formatting if enabled, and prepends the banner comment.
   *
   * @param code - The TypeScript code to format
   * @returns The formatted code with banner
   */
  async format(code: string) {
    const bannerPadding =
      this.banner && !this.banner.endsWith('\n') ? '\n\n' : ''
    const codePretty = this.prettierOptions
      ? await prettierFormat(code, this.prettierOptions)
      : code
    return `${this.banner}${bannerPadding}${codePretty}`
  }
}
