#! /usr/bin/env node

/* eslint-disable @typescript-eslint/no-namespace */
/* eslint-disable n/no-extraneous-import */
/* eslint-env node */

import { l } from '@atproto/lex'
import { LexError, LexRouter } from '@atproto/lex-server'
import { serve, upgradeWebSocket } from '@atproto/lex-server/nodejs'

// This code would typically be generated by @atproto/lex
const nsid = 'com.example.echo'
const message = l.typedObject(
  nsid,
  'message',
  l.object({
    message: l.string(),
    cursor: l.integer({ minimum: 0 }),
  }),
)
const main = l.subscription(
  nsid,
  l.params({
    message: l.string({ minLength: 1 }),
    cursor: l.optional(l.integer({ minimum: 0, default: 0 })),
  }),
  l.typedUnion([l.typedRef(() => message)], false),
  ['Completed'],
)
const com = { example: { echo: { main, message } } }

const router = new LexRouter({ upgradeWebSocket })
  //
  .add(com.example.echo, async function* ({ params: { cursor = 0, message } }) {
    for (let i = 0; ; i++) {
      yield com.example.echo.message.$build({ message, cursor: cursor + i })
      await new Promise((resolve) => setTimeout(resolve, 100))
      if (i >= 10) {
        throw new LexError(
          'Completed',
          'Subscription stopped after 10 messages. Reconnect to continue receiving messages.',
        )
      }
    }
  })

serve(
  async (request) => {
    if (request.url.includes('/xrpc/')) {
      const response = await router.fetch(request)
      response.headers.set('Access-Control-Allow-Origin', '*')
      response.headers.set('Access-Control-Allow-Methods', 'GET, POST')
      response.headers.set('Access-Control-Allow-Headers', 'Content-Type')
      response.headers.set('Access-Control-Max-Age', '86400')
      return response
    }

    return indexHtml()
  },
  { port: 8080, host: '0.0.0.0' },
)

function indexHtml() {
  return new Response(
    html`
      <h1>Not Found</h1>
      <script type="module">
        import { decodeMultiple } from 'https://cdn.jsdelivr.net/npm/cbor-x@1.6.0/+esm'

        const nsid = 'com.example.echo'
        const params = new URLSearchParams(window.location.search)

        if (!params.has('message')) {
          params.set('message', 'Hello, world!')
        }

        window.ws = new WebSocket(
          'ws://localhost:8080/xrpc/' + nsid + '?' + params.toString(),
        )
        ws.binaryType = 'arraybuffer'

        ws.addEventListener('message', async (event) => {
          const bytes = new Uint8Array(event.data)
          let { length, 0: header, 1: data } = await decodeMultiple(bytes)
          if (length !== 2) {
            console.warn('Invalid message format', bytes)
          } else if (header.op === 1) {
            if (
              data &&
              typeof data === 'object' &&
              typeof header.t === 'string' &&
              !('$type' in data)
            ) {
              data.$type = header.t.startsWith('#') ? nsid + header.t : header.t
            }

            console.log('Data', data)
          } else if (header.op === -1) {
            console.warn('Error', data)
          } else {
            console.warn('Unknown message', header, data)
          }
        })

        ws.addEventListener('close', (event) => {
          console.info('Closed', {
            code: event.code,
            reason: event.reason,
            wasClean: event.wasClean,
          })
        })

        setTimeout(() => {
          ws.close()
        }, 20_000)
      </script>
    `,
    {
      status: 404,
      headers: { 'content-type': 'text/html' },
    },
  )
}

/**
 * Simple HTML template tag function to enable syntax highlighting.
 * @param {TemplateStringsArray} parts
 * @param {...never} args
 * @returns {string}
 */
function html(parts, ...args) {
  if (args.length) throw new Error('No substitutions allowed in HTML template')
  return parts[0]
}
