// @generated by protoc-gen-connect-es v1.3.0 with parameter "target=ts,import_extension="
// @generated from file bsky.proto (package bsky, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import {
  CleanupTombstonedActorRequest,
  CleanupTombstonedActorResponse,
  ClearActorMutelistSubscriptionsRequest,
  ClearActorMutelistSubscriptionsResponse,
  ClearActorMutesRequest,
  ClearActorMutesResponse,
  ClearListmutesCacheUpdateRequest,
  ClearListmutesCacheUpdateResponse,
  CreateActorChatDeclarationRequest,
  CreateActorChatDeclarationResponse,
  CreateActorDNPRequest,
  CreateActorDNPResponse,
  CreateActorMuteFilterUpdateRequest,
  CreateActorMuteFilterUpdateResponse,
  CreateActorMutelistSubscriptionRequest,
  CreateActorMutelistSubscriptionResponse,
  CreateActorMuteRequest,
  CreateActorMuteResponse,
  CreateActorProfileRequest,
  CreateActorProfileResponse,
  CreateFeedGeneratorRequest,
  CreateFeedGeneratorResponse,
  CreateFeedGeneratorSearchDBUpdateRequest,
  CreateFeedGeneratorSearchDBUpdateResponse,
  CreateFeedLikeBatchRequest,
  CreateFeedLikeBatchResponse,
  CreateFeedLikeNotificationsRequest,
  CreateFeedLikeNotificationsResponse,
  CreateFeedLikeRequest,
  CreateFeedLikeResponse,
  CreateFeedPostListFeedFanOutRequest,
  CreateFeedPostListFeedFanOutResponse,
  CreateFeedPostNotificationsRequest,
  CreateFeedPostNotificationsResponse,
  CreateFeedPostRequest,
  CreateFeedPostResponse,
  CreateFeedPostTimelineFanOutRequest,
  CreateFeedPostTimelineFanOutResponse,
  CreateFeedRepostNotificationsRequest,
  CreateFeedRepostNotificationsResponse,
  CreateFeedRepostRequest,
  CreateFeedRepostResponse,
  CreateFeedRepostTimelineFanOutRequest,
  CreateFeedRepostTimelineFanOutResponse,
  CreateFeedThreadgateRequest,
  CreateFeedThreadgateResponse,
  CreateGraphBlockFilterUpdateRequest,
  CreateGraphBlockFilterUpdateResponse,
  CreateGraphBlockRequest,
  CreateGraphBlockResponse,
  CreateGraphFollowNotificationsRequest,
  CreateGraphFollowNotificationsResponse,
  CreateGraphFollowRequest,
  CreateGraphFollowResponse,
  CreateGraphFollowUpdateTimelineRequest,
  CreateGraphFollowUpdateTimelineResponse,
  CreateGraphListblockCacheUpdateRequest,
  CreateGraphListblockCacheUpdateResponse,
  CreateGraphListblockRequest,
  CreateGraphListblockResponse,
  CreateGraphListitemRequest,
  CreateGraphListitemResponse,
  CreateGraphListItemUpdateListFeedRequest,
  CreateGraphListItemUpdateListFeedResponse,
  CreateGraphListRequest,
  CreateGraphListResponse,
  CreateLabelerRequest,
  CreateLabelerResponse,
  CreateLabelsCacheUpdateRequest,
  CreateLabelsCacheUpdateResponse,
  CreateLabelsRequest,
  CreateLabelsResponse,
  CreateListmuteCacheUpdateRequest,
  CreateListmuteCacheUpdateResponse,
  CreateSuggestedActorsRequest,
  CreateSuggestedActorsResponse,
  CreateSuggestedEntitiesRequest,
  CreateSuggestedEntitiesResponse,
  CreateSuggestedFeedsRequest,
  CreateSuggestedFeedsResponse,
  DeleteActorChatDeclarationRequest,
  DeleteActorChatDeclarationResponse,
  DeleteActorDNPRequest,
  DeleteActorDNPResponse,
  DeleteActorMutelistSubscriptionRequest,
  DeleteActorMutelistSubscriptionResponse,
  DeleteActorMuteRequest,
  DeleteActorMuteResponse,
  DeleteActorProfileRequest,
  DeleteActorProfileResponse,
  DeleteFeedGeneratorRequest,
  DeleteFeedGeneratorResponse,
  DeleteFeedGeneratorSearchDBUpdateRequest,
  DeleteFeedGeneratorSearchDBUpdateResponse,
  DeleteFeedLikeNotificationsRequest,
  DeleteFeedLikeNotificationsResponse,
  DeleteFeedLikeRequest,
  DeleteFeedLikeResponse,
  DeleteFeedPostCacheUpdateRequest,
  DeleteFeedPostCacheUpdateResponse,
  DeleteFeedPostNotificationsRequest,
  DeleteFeedPostNotificationsResponse,
  DeleteFeedPostRequest,
  DeleteFeedPostResponse,
  DeleteFeedPostTimelineFanOutRequest,
  DeleteFeedPostTimelineFanOutResponse,
  DeleteFeedRepostNotificationsRequest,
  DeleteFeedRepostNotificationsResponse,
  DeleteFeedRepostRequest,
  DeleteFeedRepostResponse,
  DeleteFeedRepostTimelineFanOutRequest,
  DeleteFeedRepostTimelineFanOutResponse,
  DeleteFeedThreadgateRequest,
  DeleteFeedThreadgateResponse,
  DeleteGraphBlockRequest,
  DeleteGraphBlockResponse,
  DeleteGraphFollowNotificationsRequest,
  DeleteGraphFollowNotificationsResponse,
  DeleteGraphFollowRequest,
  DeleteGraphFollowResponse,
  DeleteGraphFollowUpdateTimelineRequest,
  DeleteGraphFollowUpdateTimelineResponse,
  DeleteGraphListblockCacheUpdateRequest,
  DeleteGraphListblockCacheUpdateResponse,
  DeleteGraphListblockRequest,
  DeleteGraphListblockResponse,
  DeleteGraphListitemRequest,
  DeleteGraphListitemResponse,
  DeleteGraphListItemUpdateListFeedRequest,
  DeleteGraphListItemUpdateListFeedResponse,
  DeleteGraphListRequest,
  DeleteGraphListResponse,
  DeleteLabelerRequest,
  DeleteLabelerResponse,
  DeleteListmuteCacheUpdateRequest,
  DeleteListmuteCacheUpdateResponse,
  GetActorChatDeclarationRecordsRequest,
  GetActorChatDeclarationRecordsResponse,
  GetActorFeedsRequest,
  GetActorFeedsResponse,
  GetActorFollowsActorsRequest,
  GetActorFollowsActorsResponse,
  GetActorLikesRequest,
  GetActorLikesResponse,
  GetActorListsRequest,
  GetActorListsResponse,
  GetActorMutesActorRequest,
  GetActorMutesActorResponse,
  GetActorMutesActorViaListRequest,
  GetActorMutesActorViaListResponse,
  GetActorRepostsRequest,
  GetActorRepostsResponse,
  GetActorsRequest,
  GetActorsResponse,
  GetActorTakedownRequest,
  GetActorTakedownResponse,
  GetAllLabelersRequest,
  GetAllLabelersResponse,
  GetAuthorFeedRequest,
  GetAuthorFeedResponse,
  GetBidirectionalBlockRequest,
  GetBidirectionalBlockResponse,
  GetBidirectionalBlockViaListRequest,
  GetBidirectionalBlockViaListResponse,
  GetBlobTakedownRequest,
  GetBlobTakedownResponse,
  GetBlockExistenceRequest,
  GetBlockExistenceResponse,
  GetBlocklistSubscriptionRequest,
  GetBlocklistSubscriptionResponse,
  GetBlocklistSubscriptionsRequest,
  GetBlocklistSubscriptionsResponse,
  GetBlockRecordsRequest,
  GetBlockRecordsResponse,
  GetBlocksRequest,
  GetBlocksResponse,
  GetCountsForUsersRequest,
  GetCountsForUsersResponse,
  GetDidsByHandlesRequest,
  GetDidsByHandlesResponse,
  GetDNPActorsRequest,
  GetDNPActorsResponse,
  GetFeedGeneratorRecordsRequest,
  GetFeedGeneratorRecordsResponse,
  GetFeedGeneratorStatusRequest,
  GetFeedGeneratorStatusResponse,
  GetFollowersRequest,
  GetFollowersResponse,
  GetFollowRecordsRequest,
  GetFollowRecordsResponse,
  GetFollowsFollowingRequest,
  GetFollowsFollowingResponse,
  GetFollowsRequest,
  GetFollowsResponse,
  GetFollowSuggestionsRequest,
  GetFollowSuggestionsResponse,
  GetIdentityByDidRequest,
  GetIdentityByDidResponse,
  GetIdentityByHandleRequest,
  GetIdentityByHandleResponse,
  GetInteractionCountsRequest,
  GetInteractionCountsResponse,
  GetLabelerRecordsRequest,
  GetLabelerRecordsResponse,
  GetLabelsRequest,
  GetLabelsResponse,
  GetLatestRevRequest,
  GetLatestRevResponse,
  GetLikeRecordsRequest,
  GetLikeRecordsResponse,
  GetLikesByActorAndSubjectsRequest,
  GetLikesByActorAndSubjectsResponse,
  GetLikesBySubjectRequest,
  GetLikesBySubjectResponse,
  GetLikesBySubjectSortedRequest,
  GetLikesBySubjectSortedResponse,
  GetListBlockRecordsRequest,
  GetListBlockRecordsResponse,
  GetListCountRequest,
  GetListCountResponse,
  GetListFeedRequest,
  GetListFeedResponse,
  GetListItemRecordsRequest,
  GetListItemRecordsResponse,
  GetListMembershipRequest,
  GetListMembershipResponse,
  GetListMembersRequest,
  GetListMembersResponse,
  GetListRecordsRequest,
  GetListRecordsResponse,
  GetMutelistSubscriptionRequest,
  GetMutelistSubscriptionResponse,
  GetMutelistSubscriptionsRequest,
  GetMutelistSubscriptionsResponse,
  GetMutesRequest,
  GetMutesResponse,
  GetNotificationSeenRequest,
  GetNotificationSeenResponse,
  GetNotificationsRequest,
  GetNotificationsResponse,
  GetPostRecordsRequest,
  GetPostRecordsResponse,
  GetPostReplyCountsRequest,
  GetPostReplyCountsResponse,
  GetProfileRecordsRequest,
  GetProfileRecordsResponse,
  GetRecordTakedownRequest,
  GetRecordTakedownResponse,
  GetRelationshipsRequest,
  GetRelationshipsResponse,
  GetRepostRecordsRequest,
  GetRepostRecordsResponse,
  GetRepostsByActorAndSubjectsRequest,
  GetRepostsByActorAndSubjectsResponse,
  GetRepostsBySubjectRequest,
  GetRepostsBySubjectResponse,
  GetSuggestedEntitiesRequest,
  GetSuggestedEntitiesResponse,
  GetSuggestedFeedsRequest,
  GetSuggestedFeedsResponse,
  GetThreadGateRecordsRequest,
  GetThreadGateRecordsResponse,
  GetThreadRequest,
  GetThreadResponse,
  GetTimelineRequest,
  GetTimelineResponse,
  GetUnreadNotificationCountRequest,
  GetUnreadNotificationCountResponse,
  PingRequest,
  PingResponse,
  ResurrectActorRequest,
  ResurrectActorResponse,
  RunAdminToolRequest,
  RunAdminToolResponse,
  SearchActorsRequest,
  SearchActorsResponse,
  SearchFeedGeneratorsRequest,
  SearchFeedGeneratorsResponse,
  SearchPostsRequest,
  SearchPostsResponse,
  SetupTablesRequest,
  SetupTablesResponse,
  TakedownActorRequest,
  TakedownActorResponse,
  TakedownBlobRequest,
  TakedownBlobResponse,
  TakedownPostCacheUpdateRequest,
  TakedownPostCacheUpdateResponse,
  TakedownRecordRequest,
  TakedownRecordResponse,
  TombstoneActorBlocksRequest,
  TombstoneActorBlocksResponse,
  TombstoneActorFeedgensRequest,
  TombstoneActorFeedgensResponse,
  TombstoneActorFollowsRequest,
  TombstoneActorFollowsResponse,
  TombstoneActorLikesRequest,
  TombstoneActorLikesResponse,
  TombstoneActorListblocksRequest,
  TombstoneActorListblocksResponse,
  TombstoneActorListItemsRequest,
  TombstoneActorListItemsResponse,
  TombstoneActorListsRequest,
  TombstoneActorListsResponse,
  TombstoneActorPostsRequest,
  TombstoneActorPostsResponse,
  TombstoneActorRepostsRequest,
  TombstoneActorRepostsResponse,
  TombstoneActorRequest,
  TombstoneActorResponse,
  TombstoneActorThreadgatesRequest,
  TombstoneActorThreadgatesResponse,
  UntakedownActorRequest,
  UntakedownActorResponse,
  UntakedownBlobRequest,
  UntakedownBlobResponse,
  UntakedownRecordRequest,
  UntakedownRecordResponse,
  UpdateActorChatDeclarationRequest,
  UpdateActorChatDeclarationResponse,
  UpdateActorProfileRequest,
  UpdateActorProfileResponse,
  UpdateActorUpstreamStatusRequest,
  UpdateActorUpstreamStatusResponse,
  UpdateFeedGeneratorRequest,
  UpdateFeedGeneratorResponse,
  UpdateFeedGeneratorSearchDBUpdateRequest,
  UpdateFeedGeneratorSearchDBUpdateResponse,
  UpdateFeedLikeNotificationsRequest,
  UpdateFeedLikeNotificationsResponse,
  UpdateFeedLikeRequest,
  UpdateFeedLikeResponse,
  UpdateFeedPostNotificationsRequest,
  UpdateFeedPostNotificationsResponse,
  UpdateFeedPostRequest,
  UpdateFeedPostResponse,
  UpdateFeedPostTimelineFanOutRequest,
  UpdateFeedPostTimelineFanOutResponse,
  UpdateFeedRepostNotificationsRequest,
  UpdateFeedRepostNotificationsResponse,
  UpdateFeedRepostRequest,
  UpdateFeedRepostResponse,
  UpdateFeedRepostTimelineFanOutRequest,
  UpdateFeedRepostTimelineFanOutResponse,
  UpdateFeedThreadgateRequest,
  UpdateFeedThreadgateResponse,
  UpdateGraphBlockRequest,
  UpdateGraphBlockResponse,
  UpdateGraphFollowNotificationsRequest,
  UpdateGraphFollowNotificationsResponse,
  UpdateGraphFollowRequest,
  UpdateGraphFollowResponse,
  UpdateGraphFollowUpdateTimelineRequest,
  UpdateGraphFollowUpdateTimelineResponse,
  UpdateGraphListblockRequest,
  UpdateGraphListblockResponse,
  UpdateGraphListitemRequest,
  UpdateGraphListitemResponse,
  UpdateGraphListRequest,
  UpdateGraphListResponse,
  UpdateIdentityRequest,
  UpdateIdentityResponse,
  UpdateLabelerRequest,
  UpdateLabelerResponse,
  UpdateLatestRevRequest,
  UpdateLatestRevResponse,
  UpdateNotificationSeenRequest,
  UpdateNotificationSeenResponse,
} from './bsky_pb'
import { MethodKind } from '@bufbuild/protobuf'

/**
 *
 * Read Path
 *
 *
 * @generated from service bsky.Service
 */
export const Service = {
  typeName: 'bsky.Service',
  methods: {
    /**
     * Records
     *
     * @generated from rpc bsky.Service.GetBlockRecords
     */
    getBlockRecords: {
      name: 'GetBlockRecords',
      I: GetBlockRecordsRequest,
      O: GetBlockRecordsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc bsky.Service.GetFeedGeneratorRecords
     */
    getFeedGeneratorRecords: {
      name: 'GetFeedGeneratorRecords',
      I: GetFeedGeneratorRecordsRequest,
      O: GetFeedGeneratorRecordsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc bsky.Service.GetFollowRecords
     */
    getFollowRecords: {
      name: 'GetFollowRecords',
      I: GetFollowRecordsRequest,
      O: GetFollowRecordsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc bsky.Service.GetLikeRecords
     */
    getLikeRecords: {
      name: 'GetLikeRecords',
      I: GetLikeRecordsRequest,
      O: GetLikeRecordsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc bsky.Service.GetListBlockRecords
     */
    getListBlockRecords: {
      name: 'GetListBlockRecords',
      I: GetListBlockRecordsRequest,
      O: GetListBlockRecordsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc bsky.Service.GetListItemRecords
     */
    getListItemRecords: {
      name: 'GetListItemRecords',
      I: GetListItemRecordsRequest,
      O: GetListItemRecordsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc bsky.Service.GetListRecords
     */
    getListRecords: {
      name: 'GetListRecords',
      I: GetListRecordsRequest,
      O: GetListRecordsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc bsky.Service.GetPostRecords
     */
    getPostRecords: {
      name: 'GetPostRecords',
      I: GetPostRecordsRequest,
      O: GetPostRecordsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc bsky.Service.GetProfileRecords
     */
    getProfileRecords: {
      name: 'GetProfileRecords',
      I: GetProfileRecordsRequest,
      O: GetProfileRecordsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc bsky.Service.GetActorChatDeclarationRecords
     */
    getActorChatDeclarationRecords: {
      name: 'GetActorChatDeclarationRecords',
      I: GetActorChatDeclarationRecordsRequest,
      O: GetActorChatDeclarationRecordsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc bsky.Service.GetRepostRecords
     */
    getRepostRecords: {
      name: 'GetRepostRecords',
      I: GetRepostRecordsRequest,
      O: GetRepostRecordsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc bsky.Service.GetThreadGateRecords
     */
    getThreadGateRecords: {
      name: 'GetThreadGateRecords',
      I: GetThreadGateRecordsRequest,
      O: GetThreadGateRecordsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc bsky.Service.GetLabelerRecords
     */
    getLabelerRecords: {
      name: 'GetLabelerRecords',
      I: GetLabelerRecordsRequest,
      O: GetLabelerRecordsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Follows
     *
     * @generated from rpc bsky.Service.GetActorFollowsActors
     */
    getActorFollowsActors: {
      name: 'GetActorFollowsActors',
      I: GetActorFollowsActorsRequest,
      O: GetActorFollowsActorsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc bsky.Service.GetFollowers
     */
    getFollowers: {
      name: 'GetFollowers',
      I: GetFollowersRequest,
      O: GetFollowersResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc bsky.Service.GetFollows
     */
    getFollows: {
      name: 'GetFollows',
      I: GetFollowsRequest,
      O: GetFollowsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Likes
     *
     * @generated from rpc bsky.Service.GetLikesBySubject
     */
    getLikesBySubject: {
      name: 'GetLikesBySubject',
      I: GetLikesBySubjectRequest,
      O: GetLikesBySubjectResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc bsky.Service.GetLikesBySubjectSorted
     */
    getLikesBySubjectSorted: {
      name: 'GetLikesBySubjectSorted',
      I: GetLikesBySubjectSortedRequest,
      O: GetLikesBySubjectSortedResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc bsky.Service.GetLikesByActorAndSubjects
     */
    getLikesByActorAndSubjects: {
      name: 'GetLikesByActorAndSubjects',
      I: GetLikesByActorAndSubjectsRequest,
      O: GetLikesByActorAndSubjectsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc bsky.Service.GetActorLikes
     */
    getActorLikes: {
      name: 'GetActorLikes',
      I: GetActorLikesRequest,
      O: GetActorLikesResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Reposts
     *
     * @generated from rpc bsky.Service.GetRepostsBySubject
     */
    getRepostsBySubject: {
      name: 'GetRepostsBySubject',
      I: GetRepostsBySubjectRequest,
      O: GetRepostsBySubjectResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc bsky.Service.GetRepostsByActorAndSubjects
     */
    getRepostsByActorAndSubjects: {
      name: 'GetRepostsByActorAndSubjects',
      I: GetRepostsByActorAndSubjectsRequest,
      O: GetRepostsByActorAndSubjectsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc bsky.Service.GetActorReposts
     */
    getActorReposts: {
      name: 'GetActorReposts',
      I: GetActorRepostsRequest,
      O: GetActorRepostsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Interaction Counts
     *
     * @generated from rpc bsky.Service.GetInteractionCounts
     */
    getInteractionCounts: {
      name: 'GetInteractionCounts',
      I: GetInteractionCountsRequest,
      O: GetInteractionCountsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc bsky.Service.GetCountsForUsers
     */
    getCountsForUsers: {
      name: 'GetCountsForUsers',
      I: GetCountsForUsersRequest,
      O: GetCountsForUsersResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Profile
     *
     * @generated from rpc bsky.Service.GetActors
     */
    getActors: {
      name: 'GetActors',
      I: GetActorsRequest,
      O: GetActorsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc bsky.Service.GetDidsByHandles
     */
    getDidsByHandles: {
      name: 'GetDidsByHandles',
      I: GetDidsByHandlesRequest,
      O: GetDidsByHandlesResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Relationships
     *
     * @generated from rpc bsky.Service.GetRelationships
     */
    getRelationships: {
      name: 'GetRelationships',
      I: GetRelationshipsRequest,
      O: GetRelationshipsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc bsky.Service.GetBlockExistence
     */
    getBlockExistence: {
      name: 'GetBlockExistence',
      I: GetBlockExistenceRequest,
      O: GetBlockExistenceResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Lists
     *
     * @generated from rpc bsky.Service.GetActorLists
     */
    getActorLists: {
      name: 'GetActorLists',
      I: GetActorListsRequest,
      O: GetActorListsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc bsky.Service.GetListMembers
     */
    getListMembers: {
      name: 'GetListMembers',
      I: GetListMembersRequest,
      O: GetListMembersResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc bsky.Service.GetListMembership
     */
    getListMembership: {
      name: 'GetListMembership',
      I: GetListMembershipRequest,
      O: GetListMembershipResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc bsky.Service.GetListCount
     */
    getListCount: {
      name: 'GetListCount',
      I: GetListCountRequest,
      O: GetListCountResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Mutes
     *
     * @generated from rpc bsky.Service.GetActorMutesActor
     */
    getActorMutesActor: {
      name: 'GetActorMutesActor',
      I: GetActorMutesActorRequest,
      O: GetActorMutesActorResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc bsky.Service.GetMutes
     */
    getMutes: {
      name: 'GetMutes',
      I: GetMutesRequest,
      O: GetMutesResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Mutelists
     *
     * @generated from rpc bsky.Service.GetActorMutesActorViaList
     */
    getActorMutesActorViaList: {
      name: 'GetActorMutesActorViaList',
      I: GetActorMutesActorViaListRequest,
      O: GetActorMutesActorViaListResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc bsky.Service.GetMutelistSubscription
     */
    getMutelistSubscription: {
      name: 'GetMutelistSubscription',
      I: GetMutelistSubscriptionRequest,
      O: GetMutelistSubscriptionResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc bsky.Service.GetMutelistSubscriptions
     */
    getMutelistSubscriptions: {
      name: 'GetMutelistSubscriptions',
      I: GetMutelistSubscriptionsRequest,
      O: GetMutelistSubscriptionsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Blocks
     *
     * @generated from rpc bsky.Service.GetBidirectionalBlock
     */
    getBidirectionalBlock: {
      name: 'GetBidirectionalBlock',
      I: GetBidirectionalBlockRequest,
      O: GetBidirectionalBlockResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc bsky.Service.GetBlocks
     */
    getBlocks: {
      name: 'GetBlocks',
      I: GetBlocksRequest,
      O: GetBlocksResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Blocklists
     *
     * @generated from rpc bsky.Service.GetBidirectionalBlockViaList
     */
    getBidirectionalBlockViaList: {
      name: 'GetBidirectionalBlockViaList',
      I: GetBidirectionalBlockViaListRequest,
      O: GetBidirectionalBlockViaListResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc bsky.Service.GetBlocklistSubscription
     */
    getBlocklistSubscription: {
      name: 'GetBlocklistSubscription',
      I: GetBlocklistSubscriptionRequest,
      O: GetBlocklistSubscriptionResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc bsky.Service.GetBlocklistSubscriptions
     */
    getBlocklistSubscriptions: {
      name: 'GetBlocklistSubscriptions',
      I: GetBlocklistSubscriptionsRequest,
      O: GetBlocklistSubscriptionsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Notifications
     *
     * @generated from rpc bsky.Service.GetNotifications
     */
    getNotifications: {
      name: 'GetNotifications',
      I: GetNotificationsRequest,
      O: GetNotificationsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc bsky.Service.GetNotificationSeen
     */
    getNotificationSeen: {
      name: 'GetNotificationSeen',
      I: GetNotificationSeenRequest,
      O: GetNotificationSeenResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc bsky.Service.GetUnreadNotificationCount
     */
    getUnreadNotificationCount: {
      name: 'GetUnreadNotificationCount',
      I: GetUnreadNotificationCountRequest,
      O: GetUnreadNotificationCountResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc bsky.Service.UpdateNotificationSeen
     */
    updateNotificationSeen: {
      name: 'UpdateNotificationSeen',
      I: UpdateNotificationSeenRequest,
      O: UpdateNotificationSeenResponse,
      kind: MethodKind.Unary,
    },
    /**
     * FeedGenerators
     *
     * @generated from rpc bsky.Service.GetActorFeeds
     */
    getActorFeeds: {
      name: 'GetActorFeeds',
      I: GetActorFeedsRequest,
      O: GetActorFeedsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc bsky.Service.GetSuggestedFeeds
     */
    getSuggestedFeeds: {
      name: 'GetSuggestedFeeds',
      I: GetSuggestedFeedsRequest,
      O: GetSuggestedFeedsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc bsky.Service.GetFeedGeneratorStatus
     */
    getFeedGeneratorStatus: {
      name: 'GetFeedGeneratorStatus',
      I: GetFeedGeneratorStatusRequest,
      O: GetFeedGeneratorStatusResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc bsky.Service.SearchFeedGenerators
     */
    searchFeedGenerators: {
      name: 'SearchFeedGenerators',
      I: SearchFeedGeneratorsRequest,
      O: SearchFeedGeneratorsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Feeds
     *
     * @generated from rpc bsky.Service.GetAuthorFeed
     */
    getAuthorFeed: {
      name: 'GetAuthorFeed',
      I: GetAuthorFeedRequest,
      O: GetAuthorFeedResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc bsky.Service.GetTimeline
     */
    getTimeline: {
      name: 'GetTimeline',
      I: GetTimelineRequest,
      O: GetTimelineResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc bsky.Service.GetListFeed
     */
    getListFeed: {
      name: 'GetListFeed',
      I: GetListFeedRequest,
      O: GetListFeedResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Threads
     *
     * @generated from rpc bsky.Service.GetThread
     */
    getThread: {
      name: 'GetThread',
      I: GetThreadRequest,
      O: GetThreadResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Search
     *
     * @generated from rpc bsky.Service.SearchActors
     */
    searchActors: {
      name: 'SearchActors',
      I: SearchActorsRequest,
      O: SearchActorsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc bsky.Service.SearchPosts
     */
    searchPosts: {
      name: 'SearchPosts',
      I: SearchPostsRequest,
      O: SearchPostsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Suggestions
     *
     * @generated from rpc bsky.Service.GetFollowSuggestions
     */
    getFollowSuggestions: {
      name: 'GetFollowSuggestions',
      I: GetFollowSuggestionsRequest,
      O: GetFollowSuggestionsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc bsky.Service.GetSuggestedEntities
     */
    getSuggestedEntities: {
      name: 'GetSuggestedEntities',
      I: GetSuggestedEntitiesRequest,
      O: GetSuggestedEntitiesResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Posts
     *
     * @generated from rpc bsky.Service.GetPostReplyCounts
     */
    getPostReplyCounts: {
      name: 'GetPostReplyCounts',
      I: GetPostReplyCountsRequest,
      O: GetPostReplyCountsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Labels
     *
     * @generated from rpc bsky.Service.GetLabels
     */
    getLabels: {
      name: 'GetLabels',
      I: GetLabelsRequest,
      O: GetLabelsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc bsky.Service.GetAllLabelers
     */
    getAllLabelers: {
      name: 'GetAllLabelers',
      I: GetAllLabelersRequest,
      O: GetAllLabelersResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Sync
     *
     * @generated from rpc bsky.Service.GetLatestRev
     */
    getLatestRev: {
      name: 'GetLatestRev',
      I: GetLatestRevRequest,
      O: GetLatestRevResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Moderation
     *
     * @generated from rpc bsky.Service.GetBlobTakedown
     */
    getBlobTakedown: {
      name: 'GetBlobTakedown',
      I: GetBlobTakedownRequest,
      O: GetBlobTakedownResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc bsky.Service.GetRecordTakedown
     */
    getRecordTakedown: {
      name: 'GetRecordTakedown',
      I: GetRecordTakedownRequest,
      O: GetRecordTakedownResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc bsky.Service.GetActorTakedown
     */
    getActorTakedown: {
      name: 'GetActorTakedown',
      I: GetActorTakedownRequest,
      O: GetActorTakedownResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Identity
     *
     * @generated from rpc bsky.Service.GetIdentityByDid
     */
    getIdentityByDid: {
      name: 'GetIdentityByDid',
      I: GetIdentityByDidRequest,
      O: GetIdentityByDidResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc bsky.Service.GetIdentityByHandle
     */
    getIdentityByHandle: {
      name: 'GetIdentityByHandle',
      I: GetIdentityByHandleRequest,
      O: GetIdentityByHandleResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Graph
     *
     * @generated from rpc bsky.Service.GetFollowsFollowing
     */
    getFollowsFollowing: {
      name: 'GetFollowsFollowing',
      I: GetFollowsFollowingRequest,
      O: GetFollowsFollowingResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Ping
     *
     * @generated from rpc bsky.Service.Ping
     */
    ping: {
      name: 'Ping',
      I: PingRequest,
      O: PingResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Setup
     *
     * @generated from rpc bsky.Service.SetupTables
     */
    setupTables: {
      name: 'SetupTables',
      I: SetupTablesRequest,
      O: SetupTablesResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Identity
     *
     * @generated from rpc bsky.Service.UpdateIdentity
     */
    updateIdentity: {
      name: 'UpdateIdentity',
      I: UpdateIdentityRequest,
      O: UpdateIdentityResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Sync
     *
     * @generated from rpc bsky.Service.UpdateLatestRev
     */
    updateLatestRev: {
      name: 'UpdateLatestRev',
      I: UpdateLatestRevRequest,
      O: UpdateLatestRevResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Labels
     *
     * @generated from rpc bsky.Service.CreateLabels
     */
    createLabels: {
      name: 'CreateLabels',
      I: CreateLabelsRequest,
      O: CreateLabelsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc bsky.Service.CreateLabelsCacheUpdate
     */
    createLabelsCacheUpdate: {
      name: 'CreateLabelsCacheUpdate',
      I: CreateLabelsCacheUpdateRequest,
      O: CreateLabelsCacheUpdateResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Moderation
     *
     * @generated from rpc bsky.Service.TakedownBlob
     */
    takedownBlob: {
      name: 'TakedownBlob',
      I: TakedownBlobRequest,
      O: TakedownBlobResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc bsky.Service.TakedownRecord
     */
    takedownRecord: {
      name: 'TakedownRecord',
      I: TakedownRecordRequest,
      O: TakedownRecordResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc bsky.Service.TakedownActor
     */
    takedownActor: {
      name: 'TakedownActor',
      I: TakedownActorRequest,
      O: TakedownActorResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc bsky.Service.UpdateActorUpstreamStatus
     */
    updateActorUpstreamStatus: {
      name: 'UpdateActorUpstreamStatus',
      I: UpdateActorUpstreamStatusRequest,
      O: UpdateActorUpstreamStatusResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc bsky.Service.UntakedownBlob
     */
    untakedownBlob: {
      name: 'UntakedownBlob',
      I: UntakedownBlobRequest,
      O: UntakedownBlobResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc bsky.Service.UntakedownRecord
     */
    untakedownRecord: {
      name: 'UntakedownRecord',
      I: UntakedownRecordRequest,
      O: UntakedownRecordResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc bsky.Service.UntakedownActor
     */
    untakedownActor: {
      name: 'UntakedownActor',
      I: UntakedownActorRequest,
      O: UntakedownActorResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Caches
     *
     * @generated from rpc bsky.Service.CreateGraphBlockFilterUpdate
     */
    createGraphBlockFilterUpdate: {
      name: 'CreateGraphBlockFilterUpdate',
      I: CreateGraphBlockFilterUpdateRequest,
      O: CreateGraphBlockFilterUpdateResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc bsky.Service.CreateActorMuteFilterUpdate
     */
    createActorMuteFilterUpdate: {
      name: 'CreateActorMuteFilterUpdate',
      I: CreateActorMuteFilterUpdateRequest,
      O: CreateActorMuteFilterUpdateResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc bsky.Service.CreateGraphListblockCacheUpdate
     */
    createGraphListblockCacheUpdate: {
      name: 'CreateGraphListblockCacheUpdate',
      I: CreateGraphListblockCacheUpdateRequest,
      O: CreateGraphListblockCacheUpdateResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc bsky.Service.DeleteGraphListblockCacheUpdate
     */
    deleteGraphListblockCacheUpdate: {
      name: 'DeleteGraphListblockCacheUpdate',
      I: DeleteGraphListblockCacheUpdateRequest,
      O: DeleteGraphListblockCacheUpdateResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc bsky.Service.DeleteFeedPostCacheUpdate
     */
    deleteFeedPostCacheUpdate: {
      name: 'DeleteFeedPostCacheUpdate',
      I: DeleteFeedPostCacheUpdateRequest,
      O: DeleteFeedPostCacheUpdateResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc bsky.Service.TakedownPostCacheUpdate
     */
    takedownPostCacheUpdate: {
      name: 'TakedownPostCacheUpdate',
      I: TakedownPostCacheUpdateRequest,
      O: TakedownPostCacheUpdateResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc bsky.Service.CreateFeedGeneratorSearchDBUpdate
     */
    createFeedGeneratorSearchDBUpdate: {
      name: 'CreateFeedGeneratorSearchDBUpdate',
      I: CreateFeedGeneratorSearchDBUpdateRequest,
      O: CreateFeedGeneratorSearchDBUpdateResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc bsky.Service.UpdateFeedGeneratorSearchDBUpdate
     */
    updateFeedGeneratorSearchDBUpdate: {
      name: 'UpdateFeedGeneratorSearchDBUpdate',
      I: UpdateFeedGeneratorSearchDBUpdateRequest,
      O: UpdateFeedGeneratorSearchDBUpdateResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc bsky.Service.DeleteFeedGeneratorSearchDBUpdate
     */
    deleteFeedGeneratorSearchDBUpdate: {
      name: 'DeleteFeedGeneratorSearchDBUpdate',
      I: DeleteFeedGeneratorSearchDBUpdateRequest,
      O: DeleteFeedGeneratorSearchDBUpdateResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc bsky.Service.CreateListmuteCacheUpdate
     */
    createListmuteCacheUpdate: {
      name: 'CreateListmuteCacheUpdate',
      I: CreateListmuteCacheUpdateRequest,
      O: CreateListmuteCacheUpdateResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc bsky.Service.DeleteListmuteCacheUpdate
     */
    deleteListmuteCacheUpdate: {
      name: 'DeleteListmuteCacheUpdate',
      I: DeleteListmuteCacheUpdateRequest,
      O: DeleteListmuteCacheUpdateResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc bsky.Service.ClearListmutesCacheUpdate
     */
    clearListmutesCacheUpdate: {
      name: 'ClearListmutesCacheUpdate',
      I: ClearListmutesCacheUpdateRequest,
      O: ClearListmutesCacheUpdateResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Ingestion
     *
     * @generated from rpc bsky.Service.CreateFeedPost
     */
    createFeedPost: {
      name: 'CreateFeedPost',
      I: CreateFeedPostRequest,
      O: CreateFeedPostResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc bsky.Service.DeleteFeedPost
     */
    deleteFeedPost: {
      name: 'DeleteFeedPost',
      I: DeleteFeedPostRequest,
      O: DeleteFeedPostResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc bsky.Service.UpdateFeedPost
     */
    updateFeedPost: {
      name: 'UpdateFeedPost',
      I: UpdateFeedPostRequest,
      O: UpdateFeedPostResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc bsky.Service.CreateFeedPostNotifications
     */
    createFeedPostNotifications: {
      name: 'CreateFeedPostNotifications',
      I: CreateFeedPostNotificationsRequest,
      O: CreateFeedPostNotificationsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc bsky.Service.DeleteFeedPostNotifications
     */
    deleteFeedPostNotifications: {
      name: 'DeleteFeedPostNotifications',
      I: DeleteFeedPostNotificationsRequest,
      O: DeleteFeedPostNotificationsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc bsky.Service.UpdateFeedPostNotifications
     */
    updateFeedPostNotifications: {
      name: 'UpdateFeedPostNotifications',
      I: UpdateFeedPostNotificationsRequest,
      O: UpdateFeedPostNotificationsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc bsky.Service.CreateFeedPostTimelineFanOut
     */
    createFeedPostTimelineFanOut: {
      name: 'CreateFeedPostTimelineFanOut',
      I: CreateFeedPostTimelineFanOutRequest,
      O: CreateFeedPostTimelineFanOutResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc bsky.Service.DeleteFeedPostTimelineFanOut
     */
    deleteFeedPostTimelineFanOut: {
      name: 'DeleteFeedPostTimelineFanOut',
      I: DeleteFeedPostTimelineFanOutRequest,
      O: DeleteFeedPostTimelineFanOutResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc bsky.Service.UpdateFeedPostTimelineFanOut
     */
    updateFeedPostTimelineFanOut: {
      name: 'UpdateFeedPostTimelineFanOut',
      I: UpdateFeedPostTimelineFanOutRequest,
      O: UpdateFeedPostTimelineFanOutResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc bsky.Service.CreateFeedPostListFeedFanOut
     */
    createFeedPostListFeedFanOut: {
      name: 'CreateFeedPostListFeedFanOut',
      I: CreateFeedPostListFeedFanOutRequest,
      O: CreateFeedPostListFeedFanOutResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc bsky.Service.CreateGraphListItemUpdateListFeed
     */
    createGraphListItemUpdateListFeed: {
      name: 'CreateGraphListItemUpdateListFeed',
      I: CreateGraphListItemUpdateListFeedRequest,
      O: CreateGraphListItemUpdateListFeedResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc bsky.Service.DeleteGraphListItemUpdateListFeed
     */
    deleteGraphListItemUpdateListFeed: {
      name: 'DeleteGraphListItemUpdateListFeed',
      I: DeleteGraphListItemUpdateListFeedRequest,
      O: DeleteGraphListItemUpdateListFeedResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc bsky.Service.CreateFeedRepost
     */
    createFeedRepost: {
      name: 'CreateFeedRepost',
      I: CreateFeedRepostRequest,
      O: CreateFeedRepostResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc bsky.Service.DeleteFeedRepost
     */
    deleteFeedRepost: {
      name: 'DeleteFeedRepost',
      I: DeleteFeedRepostRequest,
      O: DeleteFeedRepostResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc bsky.Service.UpdateFeedRepost
     */
    updateFeedRepost: {
      name: 'UpdateFeedRepost',
      I: UpdateFeedRepostRequest,
      O: UpdateFeedRepostResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc bsky.Service.CreateFeedRepostNotifications
     */
    createFeedRepostNotifications: {
      name: 'CreateFeedRepostNotifications',
      I: CreateFeedRepostNotificationsRequest,
      O: CreateFeedRepostNotificationsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc bsky.Service.DeleteFeedRepostNotifications
     */
    deleteFeedRepostNotifications: {
      name: 'DeleteFeedRepostNotifications',
      I: DeleteFeedRepostNotificationsRequest,
      O: DeleteFeedRepostNotificationsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc bsky.Service.UpdateFeedRepostNotifications
     */
    updateFeedRepostNotifications: {
      name: 'UpdateFeedRepostNotifications',
      I: UpdateFeedRepostNotificationsRequest,
      O: UpdateFeedRepostNotificationsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc bsky.Service.CreateFeedRepostTimelineFanOut
     */
    createFeedRepostTimelineFanOut: {
      name: 'CreateFeedRepostTimelineFanOut',
      I: CreateFeedRepostTimelineFanOutRequest,
      O: CreateFeedRepostTimelineFanOutResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc bsky.Service.DeleteFeedRepostTimelineFanOut
     */
    deleteFeedRepostTimelineFanOut: {
      name: 'DeleteFeedRepostTimelineFanOut',
      I: DeleteFeedRepostTimelineFanOutRequest,
      O: DeleteFeedRepostTimelineFanOutResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc bsky.Service.UpdateFeedRepostTimelineFanOut
     */
    updateFeedRepostTimelineFanOut: {
      name: 'UpdateFeedRepostTimelineFanOut',
      I: UpdateFeedRepostTimelineFanOutRequest,
      O: UpdateFeedRepostTimelineFanOutResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc bsky.Service.CreateFeedLike
     */
    createFeedLike: {
      name: 'CreateFeedLike',
      I: CreateFeedLikeRequest,
      O: CreateFeedLikeResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc bsky.Service.CreateFeedLikeBatch
     */
    createFeedLikeBatch: {
      name: 'CreateFeedLikeBatch',
      I: CreateFeedLikeBatchRequest,
      O: CreateFeedLikeBatchResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc bsky.Service.DeleteFeedLike
     */
    deleteFeedLike: {
      name: 'DeleteFeedLike',
      I: DeleteFeedLikeRequest,
      O: DeleteFeedLikeResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc bsky.Service.UpdateFeedLike
     */
    updateFeedLike: {
      name: 'UpdateFeedLike',
      I: UpdateFeedLikeRequest,
      O: UpdateFeedLikeResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc bsky.Service.CreateFeedLikeNotifications
     */
    createFeedLikeNotifications: {
      name: 'CreateFeedLikeNotifications',
      I: CreateFeedLikeNotificationsRequest,
      O: CreateFeedLikeNotificationsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc bsky.Service.DeleteFeedLikeNotifications
     */
    deleteFeedLikeNotifications: {
      name: 'DeleteFeedLikeNotifications',
      I: DeleteFeedLikeNotificationsRequest,
      O: DeleteFeedLikeNotificationsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc bsky.Service.UpdateFeedLikeNotifications
     */
    updateFeedLikeNotifications: {
      name: 'UpdateFeedLikeNotifications',
      I: UpdateFeedLikeNotificationsRequest,
      O: UpdateFeedLikeNotificationsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc bsky.Service.CreateGraphFollow
     */
    createGraphFollow: {
      name: 'CreateGraphFollow',
      I: CreateGraphFollowRequest,
      O: CreateGraphFollowResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc bsky.Service.DeleteGraphFollow
     */
    deleteGraphFollow: {
      name: 'DeleteGraphFollow',
      I: DeleteGraphFollowRequest,
      O: DeleteGraphFollowResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc bsky.Service.UpdateGraphFollow
     */
    updateGraphFollow: {
      name: 'UpdateGraphFollow',
      I: UpdateGraphFollowRequest,
      O: UpdateGraphFollowResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc bsky.Service.CreateGraphFollowNotifications
     */
    createGraphFollowNotifications: {
      name: 'CreateGraphFollowNotifications',
      I: CreateGraphFollowNotificationsRequest,
      O: CreateGraphFollowNotificationsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc bsky.Service.DeleteGraphFollowNotifications
     */
    deleteGraphFollowNotifications: {
      name: 'DeleteGraphFollowNotifications',
      I: DeleteGraphFollowNotificationsRequest,
      O: DeleteGraphFollowNotificationsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc bsky.Service.UpdateGraphFollowNotifications
     */
    updateGraphFollowNotifications: {
      name: 'UpdateGraphFollowNotifications',
      I: UpdateGraphFollowNotificationsRequest,
      O: UpdateGraphFollowNotificationsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc bsky.Service.CreateGraphFollowUpdateTimeline
     */
    createGraphFollowUpdateTimeline: {
      name: 'CreateGraphFollowUpdateTimeline',
      I: CreateGraphFollowUpdateTimelineRequest,
      O: CreateGraphFollowUpdateTimelineResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc bsky.Service.DeleteGraphFollowUpdateTimeline
     */
    deleteGraphFollowUpdateTimeline: {
      name: 'DeleteGraphFollowUpdateTimeline',
      I: DeleteGraphFollowUpdateTimelineRequest,
      O: DeleteGraphFollowUpdateTimelineResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc bsky.Service.UpdateGraphFollowUpdateTimeline
     */
    updateGraphFollowUpdateTimeline: {
      name: 'UpdateGraphFollowUpdateTimeline',
      I: UpdateGraphFollowUpdateTimelineRequest,
      O: UpdateGraphFollowUpdateTimelineResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc bsky.Service.CreateGraphBlock
     */
    createGraphBlock: {
      name: 'CreateGraphBlock',
      I: CreateGraphBlockRequest,
      O: CreateGraphBlockResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc bsky.Service.DeleteGraphBlock
     */
    deleteGraphBlock: {
      name: 'DeleteGraphBlock',
      I: DeleteGraphBlockRequest,
      O: DeleteGraphBlockResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc bsky.Service.UpdateGraphBlock
     */
    updateGraphBlock: {
      name: 'UpdateGraphBlock',
      I: UpdateGraphBlockRequest,
      O: UpdateGraphBlockResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc bsky.Service.CreateActorProfile
     */
    createActorProfile: {
      name: 'CreateActorProfile',
      I: CreateActorProfileRequest,
      O: CreateActorProfileResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc bsky.Service.DeleteActorProfile
     */
    deleteActorProfile: {
      name: 'DeleteActorProfile',
      I: DeleteActorProfileRequest,
      O: DeleteActorProfileResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc bsky.Service.UpdateActorProfile
     */
    updateActorProfile: {
      name: 'UpdateActorProfile',
      I: UpdateActorProfileRequest,
      O: UpdateActorProfileResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc bsky.Service.CreateActorChatDeclaration
     */
    createActorChatDeclaration: {
      name: 'CreateActorChatDeclaration',
      I: CreateActorChatDeclarationRequest,
      O: CreateActorChatDeclarationResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc bsky.Service.DeleteActorChatDeclaration
     */
    deleteActorChatDeclaration: {
      name: 'DeleteActorChatDeclaration',
      I: DeleteActorChatDeclarationRequest,
      O: DeleteActorChatDeclarationResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc bsky.Service.UpdateActorChatDeclaration
     */
    updateActorChatDeclaration: {
      name: 'UpdateActorChatDeclaration',
      I: UpdateActorChatDeclarationRequest,
      O: UpdateActorChatDeclarationResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc bsky.Service.CreateLabeler
     */
    createLabeler: {
      name: 'CreateLabeler',
      I: CreateLabelerRequest,
      O: CreateLabelerResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc bsky.Service.DeleteLabeler
     */
    deleteLabeler: {
      name: 'DeleteLabeler',
      I: DeleteLabelerRequest,
      O: DeleteLabelerResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc bsky.Service.UpdateLabeler
     */
    updateLabeler: {
      name: 'UpdateLabeler',
      I: UpdateLabelerRequest,
      O: UpdateLabelerResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc bsky.Service.CreateGraphList
     */
    createGraphList: {
      name: 'CreateGraphList',
      I: CreateGraphListRequest,
      O: CreateGraphListResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc bsky.Service.DeleteGraphList
     */
    deleteGraphList: {
      name: 'DeleteGraphList',
      I: DeleteGraphListRequest,
      O: DeleteGraphListResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc bsky.Service.UpdateGraphList
     */
    updateGraphList: {
      name: 'UpdateGraphList',
      I: UpdateGraphListRequest,
      O: UpdateGraphListResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc bsky.Service.CreateGraphListitem
     */
    createGraphListitem: {
      name: 'CreateGraphListitem',
      I: CreateGraphListitemRequest,
      O: CreateGraphListitemResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc bsky.Service.DeleteGraphListitem
     */
    deleteGraphListitem: {
      name: 'DeleteGraphListitem',
      I: DeleteGraphListitemRequest,
      O: DeleteGraphListitemResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc bsky.Service.UpdateGraphListitem
     */
    updateGraphListitem: {
      name: 'UpdateGraphListitem',
      I: UpdateGraphListitemRequest,
      O: UpdateGraphListitemResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc bsky.Service.CreateGraphListblock
     */
    createGraphListblock: {
      name: 'CreateGraphListblock',
      I: CreateGraphListblockRequest,
      O: CreateGraphListblockResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc bsky.Service.DeleteGraphListblock
     */
    deleteGraphListblock: {
      name: 'DeleteGraphListblock',
      I: DeleteGraphListblockRequest,
      O: DeleteGraphListblockResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc bsky.Service.UpdateGraphListblock
     */
    updateGraphListblock: {
      name: 'UpdateGraphListblock',
      I: UpdateGraphListblockRequest,
      O: UpdateGraphListblockResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc bsky.Service.CreateFeedGenerator
     */
    createFeedGenerator: {
      name: 'CreateFeedGenerator',
      I: CreateFeedGeneratorRequest,
      O: CreateFeedGeneratorResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc bsky.Service.DeleteFeedGenerator
     */
    deleteFeedGenerator: {
      name: 'DeleteFeedGenerator',
      I: DeleteFeedGeneratorRequest,
      O: DeleteFeedGeneratorResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc bsky.Service.UpdateFeedGenerator
     */
    updateFeedGenerator: {
      name: 'UpdateFeedGenerator',
      I: UpdateFeedGeneratorRequest,
      O: UpdateFeedGeneratorResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc bsky.Service.CreateFeedThreadgate
     */
    createFeedThreadgate: {
      name: 'CreateFeedThreadgate',
      I: CreateFeedThreadgateRequest,
      O: CreateFeedThreadgateResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc bsky.Service.DeleteFeedThreadgate
     */
    deleteFeedThreadgate: {
      name: 'DeleteFeedThreadgate',
      I: DeleteFeedThreadgateRequest,
      O: DeleteFeedThreadgateResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc bsky.Service.UpdateFeedThreadgate
     */
    updateFeedThreadgate: {
      name: 'UpdateFeedThreadgate',
      I: UpdateFeedThreadgateRequest,
      O: UpdateFeedThreadgateResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc bsky.Service.TombstoneActor
     */
    tombstoneActor: {
      name: 'TombstoneActor',
      I: TombstoneActorRequest,
      O: TombstoneActorResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc bsky.Service.TombstoneActorPosts
     */
    tombstoneActorPosts: {
      name: 'TombstoneActorPosts',
      I: TombstoneActorPostsRequest,
      O: TombstoneActorPostsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc bsky.Service.TombstoneActorLikes
     */
    tombstoneActorLikes: {
      name: 'TombstoneActorLikes',
      I: TombstoneActorLikesRequest,
      O: TombstoneActorLikesResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc bsky.Service.TombstoneActorReposts
     */
    tombstoneActorReposts: {
      name: 'TombstoneActorReposts',
      I: TombstoneActorRepostsRequest,
      O: TombstoneActorRepostsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc bsky.Service.TombstoneActorFollows
     */
    tombstoneActorFollows: {
      name: 'TombstoneActorFollows',
      I: TombstoneActorFollowsRequest,
      O: TombstoneActorFollowsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc bsky.Service.TombstoneActorBlocks
     */
    tombstoneActorBlocks: {
      name: 'TombstoneActorBlocks',
      I: TombstoneActorBlocksRequest,
      O: TombstoneActorBlocksResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc bsky.Service.TombstoneActorListblocks
     */
    tombstoneActorListblocks: {
      name: 'TombstoneActorListblocks',
      I: TombstoneActorListblocksRequest,
      O: TombstoneActorListblocksResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc bsky.Service.TombstoneActorFeedgens
     */
    tombstoneActorFeedgens: {
      name: 'TombstoneActorFeedgens',
      I: TombstoneActorFeedgensRequest,
      O: TombstoneActorFeedgensResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc bsky.Service.TombstoneActorLists
     */
    tombstoneActorLists: {
      name: 'TombstoneActorLists',
      I: TombstoneActorListsRequest,
      O: TombstoneActorListsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc bsky.Service.TombstoneActorListItems
     */
    tombstoneActorListItems: {
      name: 'TombstoneActorListItems',
      I: TombstoneActorListItemsRequest,
      O: TombstoneActorListItemsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc bsky.Service.TombstoneActorThreadgates
     */
    tombstoneActorThreadgates: {
      name: 'TombstoneActorThreadgates',
      I: TombstoneActorThreadgatesRequest,
      O: TombstoneActorThreadgatesResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc bsky.Service.CleanupTombstonedActor
     */
    cleanupTombstonedActor: {
      name: 'CleanupTombstonedActor',
      I: CleanupTombstonedActorRequest,
      O: CleanupTombstonedActorResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc bsky.Service.ResurrectActor
     */
    resurrectActor: {
      name: 'ResurrectActor',
      I: ResurrectActorRequest,
      O: ResurrectActorResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc bsky.Service.CreateActorMute
     */
    createActorMute: {
      name: 'CreateActorMute',
      I: CreateActorMuteRequest,
      O: CreateActorMuteResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc bsky.Service.DeleteActorMute
     */
    deleteActorMute: {
      name: 'DeleteActorMute',
      I: DeleteActorMuteRequest,
      O: DeleteActorMuteResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc bsky.Service.ClearActorMutes
     */
    clearActorMutes: {
      name: 'ClearActorMutes',
      I: ClearActorMutesRequest,
      O: ClearActorMutesResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc bsky.Service.CreateActorMutelistSubscription
     */
    createActorMutelistSubscription: {
      name: 'CreateActorMutelistSubscription',
      I: CreateActorMutelistSubscriptionRequest,
      O: CreateActorMutelistSubscriptionResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc bsky.Service.DeleteActorMutelistSubscription
     */
    deleteActorMutelistSubscription: {
      name: 'DeleteActorMutelistSubscription',
      I: DeleteActorMutelistSubscriptionRequest,
      O: DeleteActorMutelistSubscriptionResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc bsky.Service.ClearActorMutelistSubscriptions
     */
    clearActorMutelistSubscriptions: {
      name: 'ClearActorMutelistSubscriptions',
      I: ClearActorMutelistSubscriptionsRequest,
      O: ClearActorMutelistSubscriptionsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc bsky.Service.CreateSuggestedFeeds
     */
    createSuggestedFeeds: {
      name: 'CreateSuggestedFeeds',
      I: CreateSuggestedFeedsRequest,
      O: CreateSuggestedFeedsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc bsky.Service.CreateSuggestedActors
     */
    createSuggestedActors: {
      name: 'CreateSuggestedActors',
      I: CreateSuggestedActorsRequest,
      O: CreateSuggestedActorsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc bsky.Service.CreateSuggestedEntities
     */
    createSuggestedEntities: {
      name: 'CreateSuggestedEntities',
      I: CreateSuggestedEntitiesRequest,
      O: CreateSuggestedEntitiesResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc bsky.Service.CreateActorDNP
     */
    createActorDNP: {
      name: 'CreateActorDNP',
      I: CreateActorDNPRequest,
      O: CreateActorDNPResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc bsky.Service.DeleteActorDNP
     */
    deleteActorDNP: {
      name: 'DeleteActorDNP',
      I: DeleteActorDNPRequest,
      O: DeleteActorDNPResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc bsky.Service.GetDNPActors
     */
    getDNPActors: {
      name: 'GetDNPActors',
      I: GetDNPActorsRequest,
      O: GetDNPActorsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc bsky.Service.RunAdminTool
     */
    runAdminTool: {
      name: 'RunAdminTool',
      I: RunAdminToolRequest,
      O: RunAdminToolResponse,
      kind: MethodKind.Unary,
    },
  },
} as const
