// @generated by protoc-gen-es v2.12.0 with parameter "target=ts"
// @generated from file courier.proto (package courier, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_struct, file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { JsonObject, Message } from "@bufbuild/protobuf";

/**
 * Describes the file courier.proto.
 */
export const file_courier: GenFile = /*@__PURE__*/
  fileDesc("Cg1jb3VyaWVyLnByb3RvEgdjb3VyaWVyIg0KC1BpbmdSZXF1ZXN0Ig4KDFBpbmdSZXNwb25zZSKJAgoMTm90aWZpY2F0aW9uEgoKAmlkGAEgASgJEhUKDXJlY2lwaWVudF9kaWQYAiABKAkSDQoFdGl0bGUYAyABKAkSDwoHbWVzc2FnZRgEIAEoCRIUCgxjb2xsYXBzZV9rZXkYBSABKAkSFgoOYWx3YXlzX2RlbGl2ZXIYBiABKAgSLQoJdGltZXN0YW1wGAcgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcBIrCgphZGRpdGlvbmFsGAggASgLMhcuZ29vZ2xlLnByb3RvYnVmLlN0cnVjdBIZChFjbGllbnRfY29udHJvbGxlZBgJIAEoCBIRCgl0aHJlYWRfaWQYCiABKAkiSAoYUHVzaE5vdGlmaWNhdGlvbnNSZXF1ZXN0EiwKDW5vdGlmaWNhdGlvbnMYASADKAsyFS5jb3VyaWVyLk5vdGlmaWNhdGlvbiIbChlQdXNoTm90aWZpY2F0aW9uc1Jlc3BvbnNlIogBChpSZWdpc3RlckRldmljZVRva2VuUmVxdWVzdBILCgNkaWQYASABKAkSDQoFdG9rZW4YAiABKAkSDgoGYXBwX2lkGAMgASgJEiYKCHBsYXRmb3JtGAQgASgOMhQuY291cmllci5BcHBQbGF0Zm9ybRIWCg5hZ2VfcmVzdHJpY3RlZBgFIAEoCCIdChtSZWdpc3RlckRldmljZVRva2VuUmVzcG9uc2UicgocVW5yZWdpc3RlckRldmljZVRva2VuUmVxdWVzdBILCgNkaWQYASABKAkSDQoFdG9rZW4YAiABKAkSDgoGYXBwX2lkGAMgASgJEiYKCHBsYXRmb3JtGAQgASgOMhQuY291cmllci5BcHBQbGF0Zm9ybSIfCh1VbnJlZ2lzdGVyRGV2aWNlVG9rZW5SZXNwb25zZSI+ChdTZXRBZ2VSZXN0cmljdGVkUmVxdWVzdBILCgNkaWQYASABKAkSFgoOYWdlX3Jlc3RyaWN0ZWQYAiABKAgiGgoYU2V0QWdlUmVzdHJpY3RlZFJlc3BvbnNlKnEKC0FwcFBsYXRmb3JtEhwKGEFQUF9QTEFURk9STV9VTlNQRUNJRklFRBAAEhQKEEFQUF9QTEFURk9STV9JT1MQARIYChRBUFBfUExBVEZPUk1fQU5EUk9JRBACEhQKEEFQUF9QTEFURk9STV9XRUIQAzK9AwoHU2VydmljZRIzCgRQaW5nEhQuY291cmllci5QaW5nUmVxdWVzdBoVLmNvdXJpZXIuUGluZ1Jlc3BvbnNlEloKEVB1c2hOb3RpZmljYXRpb25zEiEuY291cmllci5QdXNoTm90aWZpY2F0aW9uc1JlcXVlc3QaIi5jb3VyaWVyLlB1c2hOb3RpZmljYXRpb25zUmVzcG9uc2USYAoTUmVnaXN0ZXJEZXZpY2VUb2tlbhIjLmNvdXJpZXIuUmVnaXN0ZXJEZXZpY2VUb2tlblJlcXVlc3QaJC5jb3VyaWVyLlJlZ2lzdGVyRGV2aWNlVG9rZW5SZXNwb25zZRJmChVVbnJlZ2lzdGVyRGV2aWNlVG9rZW4SJS5jb3VyaWVyLlVucmVnaXN0ZXJEZXZpY2VUb2tlblJlcXVlc3QaJi5jb3VyaWVyLlVucmVnaXN0ZXJEZXZpY2VUb2tlblJlc3BvbnNlElcKEFNldEFnZVJlc3RyaWN0ZWQSIC5jb3VyaWVyLlNldEFnZVJlc3RyaWN0ZWRSZXF1ZXN0GiEuY291cmllci5TZXRBZ2VSZXN0cmljdGVkUmVzcG9uc2VCDFoKLi87Y291cmllcmIGcHJvdG8z", [file_google_protobuf_struct, file_google_protobuf_timestamp]);

/**
 * Ping
 *
 * @generated from message courier.PingRequest
 */
export type PingRequest = Message<"courier.PingRequest"> & {
};

/**
 * Describes the message courier.PingRequest.
 * Use `create(PingRequestSchema)` to create a new message.
 */
export const PingRequestSchema: GenMessage<PingRequest> = /*@__PURE__*/
  messageDesc(file_courier, 0);

/**
 * @generated from message courier.PingResponse
 */
export type PingResponse = Message<"courier.PingResponse"> & {
};

/**
 * Describes the message courier.PingResponse.
 * Use `create(PingResponseSchema)` to create a new message.
 */
export const PingResponseSchema: GenMessage<PingResponse> = /*@__PURE__*/
  messageDesc(file_courier, 1);

/**
 * @generated from message courier.Notification
 */
export type Notification = Message<"courier.Notification"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string recipient_did = 2;
   */
  recipientDid: string;

  /**
   * @generated from field: string title = 3;
   */
  title: string;

  /**
   * @generated from field: string message = 4;
   */
  message: string;

  /**
   * @generated from field: string collapse_key = 5;
   */
  collapseKey: string;

  /**
   * @generated from field: bool always_deliver = 6;
   */
  alwaysDeliver: boolean;

  /**
   * @generated from field: google.protobuf.Timestamp timestamp = 7;
   */
  timestamp?: Timestamp | undefined;

  /**
   * @generated from field: google.protobuf.Struct additional = 8;
   */
  additional?: JsonObject | undefined;

  /**
   * @generated from field: bool client_controlled = 9;
   */
  clientControlled: boolean;

  /**
   * Maps to iOS's `thread-id`: https://developer.apple.com/documentation/usernotifications/generating-a-remote-notification.
   *
   * @generated from field: string thread_id = 10;
   */
  threadId: string;
};

/**
 * Describes the message courier.Notification.
 * Use `create(NotificationSchema)` to create a new message.
 */
export const NotificationSchema: GenMessage<Notification> = /*@__PURE__*/
  messageDesc(file_courier, 2);

/**
 * @generated from message courier.PushNotificationsRequest
 */
export type PushNotificationsRequest = Message<"courier.PushNotificationsRequest"> & {
  /**
   * @generated from field: repeated courier.Notification notifications = 1;
   */
  notifications: Notification[];
};

/**
 * Describes the message courier.PushNotificationsRequest.
 * Use `create(PushNotificationsRequestSchema)` to create a new message.
 */
export const PushNotificationsRequestSchema: GenMessage<PushNotificationsRequest> = /*@__PURE__*/
  messageDesc(file_courier, 3);

/**
 * @generated from message courier.PushNotificationsResponse
 */
export type PushNotificationsResponse = Message<"courier.PushNotificationsResponse"> & {
};

/**
 * Describes the message courier.PushNotificationsResponse.
 * Use `create(PushNotificationsResponseSchema)` to create a new message.
 */
export const PushNotificationsResponseSchema: GenMessage<PushNotificationsResponse> = /*@__PURE__*/
  messageDesc(file_courier, 4);

/**
 * @generated from message courier.RegisterDeviceTokenRequest
 */
export type RegisterDeviceTokenRequest = Message<"courier.RegisterDeviceTokenRequest"> & {
  /**
   * @generated from field: string did = 1;
   */
  did: string;

  /**
   * @generated from field: string token = 2;
   */
  token: string;

  /**
   * @generated from field: string app_id = 3;
   */
  appId: string;

  /**
   * @generated from field: courier.AppPlatform platform = 4;
   */
  platform: AppPlatform;

  /**
   * @generated from field: bool age_restricted = 5;
   */
  ageRestricted: boolean;
};

/**
 * Describes the message courier.RegisterDeviceTokenRequest.
 * Use `create(RegisterDeviceTokenRequestSchema)` to create a new message.
 */
export const RegisterDeviceTokenRequestSchema: GenMessage<RegisterDeviceTokenRequest> = /*@__PURE__*/
  messageDesc(file_courier, 5);

/**
 * @generated from message courier.RegisterDeviceTokenResponse
 */
export type RegisterDeviceTokenResponse = Message<"courier.RegisterDeviceTokenResponse"> & {
};

/**
 * Describes the message courier.RegisterDeviceTokenResponse.
 * Use `create(RegisterDeviceTokenResponseSchema)` to create a new message.
 */
export const RegisterDeviceTokenResponseSchema: GenMessage<RegisterDeviceTokenResponse> = /*@__PURE__*/
  messageDesc(file_courier, 6);

/**
 * @generated from message courier.UnregisterDeviceTokenRequest
 */
export type UnregisterDeviceTokenRequest = Message<"courier.UnregisterDeviceTokenRequest"> & {
  /**
   * @generated from field: string did = 1;
   */
  did: string;

  /**
   * @generated from field: string token = 2;
   */
  token: string;

  /**
   * @generated from field: string app_id = 3;
   */
  appId: string;

  /**
   * @generated from field: courier.AppPlatform platform = 4;
   */
  platform: AppPlatform;
};

/**
 * Describes the message courier.UnregisterDeviceTokenRequest.
 * Use `create(UnregisterDeviceTokenRequestSchema)` to create a new message.
 */
export const UnregisterDeviceTokenRequestSchema: GenMessage<UnregisterDeviceTokenRequest> = /*@__PURE__*/
  messageDesc(file_courier, 7);

/**
 * @generated from message courier.UnregisterDeviceTokenResponse
 */
export type UnregisterDeviceTokenResponse = Message<"courier.UnregisterDeviceTokenResponse"> & {
};

/**
 * Describes the message courier.UnregisterDeviceTokenResponse.
 * Use `create(UnregisterDeviceTokenResponseSchema)` to create a new message.
 */
export const UnregisterDeviceTokenResponseSchema: GenMessage<UnregisterDeviceTokenResponse> = /*@__PURE__*/
  messageDesc(file_courier, 8);

/**
 * @generated from message courier.SetAgeRestrictedRequest
 */
export type SetAgeRestrictedRequest = Message<"courier.SetAgeRestrictedRequest"> & {
  /**
   * @generated from field: string did = 1;
   */
  did: string;

  /**
   * @generated from field: bool age_restricted = 2;
   */
  ageRestricted: boolean;
};

/**
 * Describes the message courier.SetAgeRestrictedRequest.
 * Use `create(SetAgeRestrictedRequestSchema)` to create a new message.
 */
export const SetAgeRestrictedRequestSchema: GenMessage<SetAgeRestrictedRequest> = /*@__PURE__*/
  messageDesc(file_courier, 9);

/**
 * @generated from message courier.SetAgeRestrictedResponse
 */
export type SetAgeRestrictedResponse = Message<"courier.SetAgeRestrictedResponse"> & {
};

/**
 * Describes the message courier.SetAgeRestrictedResponse.
 * Use `create(SetAgeRestrictedResponseSchema)` to create a new message.
 */
export const SetAgeRestrictedResponseSchema: GenMessage<SetAgeRestrictedResponse> = /*@__PURE__*/
  messageDesc(file_courier, 10);

/**
 * @generated from enum courier.AppPlatform
 */
export enum AppPlatform {
  /**
   * @generated from enum value: APP_PLATFORM_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: APP_PLATFORM_IOS = 1;
   */
  IOS = 1,

  /**
   * @generated from enum value: APP_PLATFORM_ANDROID = 2;
   */
  ANDROID = 2,

  /**
   * @generated from enum value: APP_PLATFORM_WEB = 3;
   */
  WEB = 3,
}

/**
 * Describes the enum courier.AppPlatform.
 */
export const AppPlatformSchema: GenEnum<AppPlatform> = /*@__PURE__*/
  enumDesc(file_courier, 0);

/**
 * @generated from service courier.Service
 */
export const Service: GenService<{
  /**
   * @generated from rpc courier.Service.Ping
   */
  ping: {
    methodKind: "unary";
    input: typeof PingRequestSchema;
    output: typeof PingResponseSchema;
  },
  /**
   * @generated from rpc courier.Service.PushNotifications
   */
  pushNotifications: {
    methodKind: "unary";
    input: typeof PushNotificationsRequestSchema;
    output: typeof PushNotificationsResponseSchema;
  },
  /**
   * @generated from rpc courier.Service.RegisterDeviceToken
   */
  registerDeviceToken: {
    methodKind: "unary";
    input: typeof RegisterDeviceTokenRequestSchema;
    output: typeof RegisterDeviceTokenResponseSchema;
  },
  /**
   * @generated from rpc courier.Service.UnregisterDeviceToken
   */
  unregisterDeviceToken: {
    methodKind: "unary";
    input: typeof UnregisterDeviceTokenRequestSchema;
    output: typeof UnregisterDeviceTokenResponseSchema;
  },
  /**
   * @generated from rpc courier.Service.SetAgeRestricted
   */
  setAgeRestricted: {
    methodKind: "unary";
    input: typeof SetAgeRestrictedRequestSchema;
    output: typeof SetAgeRestrictedResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_courier, 0);

