// @generated by protoc-gen-es v1.6.0 with parameter "target=ts,import_extension="
// @generated from file sokaa.proto (package sokaa, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type {
  BinaryReadOptions,
  FieldList,
  JsonReadOptions,
  JsonValue,
  PartialMessage,
  PlainMessage,
} from '@bufbuild/protobuf'
import { Message, proto3 } from '@bufbuild/protobuf'

/**
 * @generated from message sokaa.FeedItem
 */
export class FeedItem extends Message<FeedItem> {
  /**
   * @generated from field: string uri = 1;
   */
  uri = ''

  /**
   * @generated from field: string cid = 2;
   */
  cid = ''

  constructor(data?: PartialMessage<FeedItem>) {
    super()
    proto3.util.initPartial(data, this)
  }

  static readonly runtime: typeof proto3 = proto3
  static readonly typeName = 'sokaa.FeedItem'
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: 'uri', kind: 'scalar', T: 9 /* ScalarType.STRING */ },
    { no: 2, name: 'cid', kind: 'scalar', T: 9 /* ScalarType.STRING */ },
  ])

  static fromBinary(
    bytes: Uint8Array,
    options?: Partial<BinaryReadOptions>,
  ): FeedItem {
    return new FeedItem().fromBinary(bytes, options)
  }

  static fromJson(
    jsonValue: JsonValue,
    options?: Partial<JsonReadOptions>,
  ): FeedItem {
    return new FeedItem().fromJson(jsonValue, options)
  }

  static fromJsonString(
    jsonString: string,
    options?: Partial<JsonReadOptions>,
  ): FeedItem {
    return new FeedItem().fromJsonString(jsonString, options)
  }

  static equals(
    a: FeedItem | PlainMessage<FeedItem> | undefined,
    b: FeedItem | PlainMessage<FeedItem> | undefined,
  ): boolean {
    return proto3.util.equals(FeedItem, a, b)
  }
}

/**
 * @generated from message sokaa.GetTimelineRequest
 */
export class GetTimelineRequest extends Message<GetTimelineRequest> {
  /**
   * @generated from field: string actor_did = 1;
   */
  actorDid = ''

  /**
   * @generated from field: int32 limit = 2;
   */
  limit = 0

  /**
   * @generated from field: string cursor = 3;
   */
  cursor = ''

  constructor(data?: PartialMessage<GetTimelineRequest>) {
    super()
    proto3.util.initPartial(data, this)
  }

  static readonly runtime: typeof proto3 = proto3
  static readonly typeName = 'sokaa.GetTimelineRequest'
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: 'actor_did', kind: 'scalar', T: 9 /* ScalarType.STRING */ },
    { no: 2, name: 'limit', kind: 'scalar', T: 5 /* ScalarType.INT32 */ },
    { no: 3, name: 'cursor', kind: 'scalar', T: 9 /* ScalarType.STRING */ },
  ])

  static fromBinary(
    bytes: Uint8Array,
    options?: Partial<BinaryReadOptions>,
  ): GetTimelineRequest {
    return new GetTimelineRequest().fromBinary(bytes, options)
  }

  static fromJson(
    jsonValue: JsonValue,
    options?: Partial<JsonReadOptions>,
  ): GetTimelineRequest {
    return new GetTimelineRequest().fromJson(jsonValue, options)
  }

  static fromJsonString(
    jsonString: string,
    options?: Partial<JsonReadOptions>,
  ): GetTimelineRequest {
    return new GetTimelineRequest().fromJsonString(jsonString, options)
  }

  static equals(
    a: GetTimelineRequest | PlainMessage<GetTimelineRequest> | undefined,
    b: GetTimelineRequest | PlainMessage<GetTimelineRequest> | undefined,
  ): boolean {
    return proto3.util.equals(GetTimelineRequest, a, b)
  }
}

/**
 * @generated from message sokaa.GetTimelineResponse
 */
export class GetTimelineResponse extends Message<GetTimelineResponse> {
  /**
   * @generated from field: repeated sokaa.FeedItem items = 1;
   */
  items: FeedItem[] = []

  /**
   * @generated from field: string cursor = 2;
   */
  cursor = ''

  constructor(data?: PartialMessage<GetTimelineResponse>) {
    super()
    proto3.util.initPartial(data, this)
  }

  static readonly runtime: typeof proto3 = proto3
  static readonly typeName = 'sokaa.GetTimelineResponse'
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: 'items', kind: 'message', T: FeedItem, repeated: true },
    { no: 2, name: 'cursor', kind: 'scalar', T: 9 /* ScalarType.STRING */ },
  ])

  static fromBinary(
    bytes: Uint8Array,
    options?: Partial<BinaryReadOptions>,
  ): GetTimelineResponse {
    return new GetTimelineResponse().fromBinary(bytes, options)
  }

  static fromJson(
    jsonValue: JsonValue,
    options?: Partial<JsonReadOptions>,
  ): GetTimelineResponse {
    return new GetTimelineResponse().fromJson(jsonValue, options)
  }

  static fromJsonString(
    jsonString: string,
    options?: Partial<JsonReadOptions>,
  ): GetTimelineResponse {
    return new GetTimelineResponse().fromJsonString(jsonString, options)
  }

  static equals(
    a: GetTimelineResponse | PlainMessage<GetTimelineResponse> | undefined,
    b: GetTimelineResponse | PlainMessage<GetTimelineResponse> | undefined,
  ): boolean {
    return proto3.util.equals(GetTimelineResponse, a, b)
  }
}

/**
 * @generated from message sokaa.GetAuthorFeedRequest
 */
export class GetAuthorFeedRequest extends Message<GetAuthorFeedRequest> {
  /**
   * @generated from field: string actor_did = 1;
   */
  actorDid = ''

  /**
   * @generated from field: int32 limit = 2;
   */
  limit = 0

  /**
   * @generated from field: string cursor = 3;
   */
  cursor = ''

  constructor(data?: PartialMessage<GetAuthorFeedRequest>) {
    super()
    proto3.util.initPartial(data, this)
  }

  static readonly runtime: typeof proto3 = proto3
  static readonly typeName = 'sokaa.GetAuthorFeedRequest'
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: 'actor_did', kind: 'scalar', T: 9 /* ScalarType.STRING */ },
    { no: 2, name: 'limit', kind: 'scalar', T: 5 /* ScalarType.INT32 */ },
    { no: 3, name: 'cursor', kind: 'scalar', T: 9 /* ScalarType.STRING */ },
  ])

  static fromBinary(
    bytes: Uint8Array,
    options?: Partial<BinaryReadOptions>,
  ): GetAuthorFeedRequest {
    return new GetAuthorFeedRequest().fromBinary(bytes, options)
  }

  static fromJson(
    jsonValue: JsonValue,
    options?: Partial<JsonReadOptions>,
  ): GetAuthorFeedRequest {
    return new GetAuthorFeedRequest().fromJson(jsonValue, options)
  }

  static fromJsonString(
    jsonString: string,
    options?: Partial<JsonReadOptions>,
  ): GetAuthorFeedRequest {
    return new GetAuthorFeedRequest().fromJsonString(jsonString, options)
  }

  static equals(
    a: GetAuthorFeedRequest | PlainMessage<GetAuthorFeedRequest> | undefined,
    b: GetAuthorFeedRequest | PlainMessage<GetAuthorFeedRequest> | undefined,
  ): boolean {
    return proto3.util.equals(GetAuthorFeedRequest, a, b)
  }
}

/**
 * @generated from message sokaa.GetAuthorFeedResponse
 */
export class GetAuthorFeedResponse extends Message<GetAuthorFeedResponse> {
  /**
   * @generated from field: repeated sokaa.FeedItem items = 1;
   */
  items: FeedItem[] = []

  /**
   * @generated from field: string cursor = 2;
   */
  cursor = ''

  constructor(data?: PartialMessage<GetAuthorFeedResponse>) {
    super()
    proto3.util.initPartial(data, this)
  }

  static readonly runtime: typeof proto3 = proto3
  static readonly typeName = 'sokaa.GetAuthorFeedResponse'
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: 'items', kind: 'message', T: FeedItem, repeated: true },
    { no: 2, name: 'cursor', kind: 'scalar', T: 9 /* ScalarType.STRING */ },
  ])

  static fromBinary(
    bytes: Uint8Array,
    options?: Partial<BinaryReadOptions>,
  ): GetAuthorFeedResponse {
    return new GetAuthorFeedResponse().fromBinary(bytes, options)
  }

  static fromJson(
    jsonValue: JsonValue,
    options?: Partial<JsonReadOptions>,
  ): GetAuthorFeedResponse {
    return new GetAuthorFeedResponse().fromJson(jsonValue, options)
  }

  static fromJsonString(
    jsonString: string,
    options?: Partial<JsonReadOptions>,
  ): GetAuthorFeedResponse {
    return new GetAuthorFeedResponse().fromJsonString(jsonString, options)
  }

  static equals(
    a: GetAuthorFeedResponse | PlainMessage<GetAuthorFeedResponse> | undefined,
    b: GetAuthorFeedResponse | PlainMessage<GetAuthorFeedResponse> | undefined,
  ): boolean {
    return proto3.util.equals(GetAuthorFeedResponse, a, b)
  }
}

/**
 * @generated from message sokaa.GetActorsRequest
 */
export class GetActorsRequest extends Message<GetActorsRequest> {
  /**
   * @generated from field: repeated string dids = 1;
   */
  dids: string[] = []

  constructor(data?: PartialMessage<GetActorsRequest>) {
    super()
    proto3.util.initPartial(data, this)
  }

  static readonly runtime: typeof proto3 = proto3
  static readonly typeName = 'sokaa.GetActorsRequest'
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    {
      no: 1,
      name: 'dids',
      kind: 'scalar',
      T: 9 /* ScalarType.STRING */,
      repeated: true,
    },
  ])

  static fromBinary(
    bytes: Uint8Array,
    options?: Partial<BinaryReadOptions>,
  ): GetActorsRequest {
    return new GetActorsRequest().fromBinary(bytes, options)
  }

  static fromJson(
    jsonValue: JsonValue,
    options?: Partial<JsonReadOptions>,
  ): GetActorsRequest {
    return new GetActorsRequest().fromJson(jsonValue, options)
  }

  static fromJsonString(
    jsonString: string,
    options?: Partial<JsonReadOptions>,
  ): GetActorsRequest {
    return new GetActorsRequest().fromJsonString(jsonString, options)
  }

  static equals(
    a: GetActorsRequest | PlainMessage<GetActorsRequest> | undefined,
    b: GetActorsRequest | PlainMessage<GetActorsRequest> | undefined,
  ): boolean {
    return proto3.util.equals(GetActorsRequest, a, b)
  }
}

/**
 * @generated from message sokaa.ActorInfo
 */
export class ActorInfo extends Message<ActorInfo> {
  /**
   * @generated from field: bool exists = 1;
   */
  exists = false

  /**
   * @generated from field: string handle = 2;
   */
  handle = ''

  /**
   * @generated from field: string display_name = 3;
   */
  displayName = ''

  /**
   * @generated from field: string description = 4;
   */
  description = ''

  /**
   * @generated from field: string avatar_cid = 5;
   */
  avatarCid = ''

  /**
   * @generated from field: string banner_cid = 6;
   */
  bannerCid = ''

  /**
   * @generated from field: int32 followers_count = 7;
   */
  followersCount = 0

  /**
   * @generated from field: int32 posts_count = 8;
   */
  postsCount = 0

  /**
   * @generated from field: string upstream_status = 9;
   */
  upstreamStatus = ''

  /**
   * @generated from field: string indexed_at = 10;
   */
  indexedAt = ''

  constructor(data?: PartialMessage<ActorInfo>) {
    super()
    proto3.util.initPartial(data, this)
  }

  static readonly runtime: typeof proto3 = proto3
  static readonly typeName = 'sokaa.ActorInfo'
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: 'exists', kind: 'scalar', T: 8 /* ScalarType.BOOL */ },
    { no: 2, name: 'handle', kind: 'scalar', T: 9 /* ScalarType.STRING */ },
    {
      no: 3,
      name: 'display_name',
      kind: 'scalar',
      T: 9 /* ScalarType.STRING */,
    },
    {
      no: 4,
      name: 'description',
      kind: 'scalar',
      T: 9 /* ScalarType.STRING */,
    },
    { no: 5, name: 'avatar_cid', kind: 'scalar', T: 9 /* ScalarType.STRING */ },
    { no: 6, name: 'banner_cid', kind: 'scalar', T: 9 /* ScalarType.STRING */ },
    {
      no: 7,
      name: 'followers_count',
      kind: 'scalar',
      T: 5 /* ScalarType.INT32 */,
    },
    { no: 8, name: 'posts_count', kind: 'scalar', T: 5 /* ScalarType.INT32 */ },
    {
      no: 9,
      name: 'upstream_status',
      kind: 'scalar',
      T: 9 /* ScalarType.STRING */,
    },
    {
      no: 10,
      name: 'indexed_at',
      kind: 'scalar',
      T: 9 /* ScalarType.STRING */,
    },
  ])

  static fromBinary(
    bytes: Uint8Array,
    options?: Partial<BinaryReadOptions>,
  ): ActorInfo {
    return new ActorInfo().fromBinary(bytes, options)
  }

  static fromJson(
    jsonValue: JsonValue,
    options?: Partial<JsonReadOptions>,
  ): ActorInfo {
    return new ActorInfo().fromJson(jsonValue, options)
  }

  static fromJsonString(
    jsonString: string,
    options?: Partial<JsonReadOptions>,
  ): ActorInfo {
    return new ActorInfo().fromJsonString(jsonString, options)
  }

  static equals(
    a: ActorInfo | PlainMessage<ActorInfo> | undefined,
    b: ActorInfo | PlainMessage<ActorInfo> | undefined,
  ): boolean {
    return proto3.util.equals(ActorInfo, a, b)
  }
}

/**
 * @generated from message sokaa.GetActorsResponse
 */
export class GetActorsResponse extends Message<GetActorsResponse> {
  /**
   * @generated from field: repeated sokaa.ActorInfo actors = 1;
   */
  actors: ActorInfo[] = []

  constructor(data?: PartialMessage<GetActorsResponse>) {
    super()
    proto3.util.initPartial(data, this)
  }

  static readonly runtime: typeof proto3 = proto3
  static readonly typeName = 'sokaa.GetActorsResponse'
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: 'actors', kind: 'message', T: ActorInfo, repeated: true },
  ])

  static fromBinary(
    bytes: Uint8Array,
    options?: Partial<BinaryReadOptions>,
  ): GetActorsResponse {
    return new GetActorsResponse().fromBinary(bytes, options)
  }

  static fromJson(
    jsonValue: JsonValue,
    options?: Partial<JsonReadOptions>,
  ): GetActorsResponse {
    return new GetActorsResponse().fromJson(jsonValue, options)
  }

  static fromJsonString(
    jsonString: string,
    options?: Partial<JsonReadOptions>,
  ): GetActorsResponse {
    return new GetActorsResponse().fromJsonString(jsonString, options)
  }

  static equals(
    a: GetActorsResponse | PlainMessage<GetActorsResponse> | undefined,
    b: GetActorsResponse | PlainMessage<GetActorsResponse> | undefined,
  ): boolean {
    return proto3.util.equals(GetActorsResponse, a, b)
  }
}

/**
 * @generated from message sokaa.PostInfo
 */
export class PostInfo extends Message<PostInfo> {
  /**
   * @generated from field: bool exists = 1;
   */
  exists = false

  /**
   * @generated from field: string uri = 2;
   */
  uri = ''

  /**
   * @generated from field: string cid = 3;
   */
  cid = ''

  /**
   * @generated from field: string creator = 4;
   */
  creator = ''

  /**
   * @generated from field: string caption = 5;
   */
  caption = ''

  /**
   * @generated from field: string media_type = 6;
   */
  mediaType = ''

  /**
   * @generated from field: string media_json = 7;
   */
  mediaJson = ''

  /**
   * @generated from field: int32 like_count = 8;
   */
  likeCount = 0

  /**
   * @generated from field: string created_at = 9;
   */
  createdAt = ''

  /**
   * @generated from field: string indexed_at = 10;
   */
  indexedAt = ''

  constructor(data?: PartialMessage<PostInfo>) {
    super()
    proto3.util.initPartial(data, this)
  }

  static readonly runtime: typeof proto3 = proto3
  static readonly typeName = 'sokaa.PostInfo'
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: 'exists', kind: 'scalar', T: 8 /* ScalarType.BOOL */ },
    { no: 2, name: 'uri', kind: 'scalar', T: 9 /* ScalarType.STRING */ },
    { no: 3, name: 'cid', kind: 'scalar', T: 9 /* ScalarType.STRING */ },
    { no: 4, name: 'creator', kind: 'scalar', T: 9 /* ScalarType.STRING */ },
    { no: 5, name: 'caption', kind: 'scalar', T: 9 /* ScalarType.STRING */ },
    { no: 6, name: 'media_type', kind: 'scalar', T: 9 /* ScalarType.STRING */ },
    { no: 7, name: 'media_json', kind: 'scalar', T: 9 /* ScalarType.STRING */ },
    { no: 8, name: 'like_count', kind: 'scalar', T: 5 /* ScalarType.INT32 */ },
    { no: 9, name: 'created_at', kind: 'scalar', T: 9 /* ScalarType.STRING */ },
    {
      no: 10,
      name: 'indexed_at',
      kind: 'scalar',
      T: 9 /* ScalarType.STRING */,
    },
  ])

  static fromBinary(
    bytes: Uint8Array,
    options?: Partial<BinaryReadOptions>,
  ): PostInfo {
    return new PostInfo().fromBinary(bytes, options)
  }

  static fromJson(
    jsonValue: JsonValue,
    options?: Partial<JsonReadOptions>,
  ): PostInfo {
    return new PostInfo().fromJson(jsonValue, options)
  }

  static fromJsonString(
    jsonString: string,
    options?: Partial<JsonReadOptions>,
  ): PostInfo {
    return new PostInfo().fromJsonString(jsonString, options)
  }

  static equals(
    a: PostInfo | PlainMessage<PostInfo> | undefined,
    b: PostInfo | PlainMessage<PostInfo> | undefined,
  ): boolean {
    return proto3.util.equals(PostInfo, a, b)
  }
}

/**
 * @generated from message sokaa.GetPostsRequest
 */
export class GetPostsRequest extends Message<GetPostsRequest> {
  /**
   * @generated from field: repeated string uris = 1;
   */
  uris: string[] = []

  constructor(data?: PartialMessage<GetPostsRequest>) {
    super()
    proto3.util.initPartial(data, this)
  }

  static readonly runtime: typeof proto3 = proto3
  static readonly typeName = 'sokaa.GetPostsRequest'
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    {
      no: 1,
      name: 'uris',
      kind: 'scalar',
      T: 9 /* ScalarType.STRING */,
      repeated: true,
    },
  ])

  static fromBinary(
    bytes: Uint8Array,
    options?: Partial<BinaryReadOptions>,
  ): GetPostsRequest {
    return new GetPostsRequest().fromBinary(bytes, options)
  }

  static fromJson(
    jsonValue: JsonValue,
    options?: Partial<JsonReadOptions>,
  ): GetPostsRequest {
    return new GetPostsRequest().fromJson(jsonValue, options)
  }

  static fromJsonString(
    jsonString: string,
    options?: Partial<JsonReadOptions>,
  ): GetPostsRequest {
    return new GetPostsRequest().fromJsonString(jsonString, options)
  }

  static equals(
    a: GetPostsRequest | PlainMessage<GetPostsRequest> | undefined,
    b: GetPostsRequest | PlainMessage<GetPostsRequest> | undefined,
  ): boolean {
    return proto3.util.equals(GetPostsRequest, a, b)
  }
}

/**
 * @generated from message sokaa.GetPostsResponse
 */
export class GetPostsResponse extends Message<GetPostsResponse> {
  /**
   * @generated from field: repeated sokaa.PostInfo posts = 1;
   */
  posts: PostInfo[] = []

  constructor(data?: PartialMessage<GetPostsResponse>) {
    super()
    proto3.util.initPartial(data, this)
  }

  static readonly runtime: typeof proto3 = proto3
  static readonly typeName = 'sokaa.GetPostsResponse'
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: 'posts', kind: 'message', T: PostInfo, repeated: true },
  ])

  static fromBinary(
    bytes: Uint8Array,
    options?: Partial<BinaryReadOptions>,
  ): GetPostsResponse {
    return new GetPostsResponse().fromBinary(bytes, options)
  }

  static fromJson(
    jsonValue: JsonValue,
    options?: Partial<JsonReadOptions>,
  ): GetPostsResponse {
    return new GetPostsResponse().fromJson(jsonValue, options)
  }

  static fromJsonString(
    jsonString: string,
    options?: Partial<JsonReadOptions>,
  ): GetPostsResponse {
    return new GetPostsResponse().fromJsonString(jsonString, options)
  }

  static equals(
    a: GetPostsResponse | PlainMessage<GetPostsResponse> | undefined,
    b: GetPostsResponse | PlainMessage<GetPostsResponse> | undefined,
  ): boolean {
    return proto3.util.equals(GetPostsResponse, a, b)
  }
}

/**
 * @generated from message sokaa.RecordRef
 */
export class RecordRef extends Message<RecordRef> {
  /**
   * @generated from field: string uri = 1;
   */
  uri = ''

  /**
   * @generated from field: string cid = 2;
   */
  cid = ''

  constructor(data?: PartialMessage<RecordRef>) {
    super()
    proto3.util.initPartial(data, this)
  }

  static readonly runtime: typeof proto3 = proto3
  static readonly typeName = 'sokaa.RecordRef'
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: 'uri', kind: 'scalar', T: 9 /* ScalarType.STRING */ },
    { no: 2, name: 'cid', kind: 'scalar', T: 9 /* ScalarType.STRING */ },
  ])

  static fromBinary(
    bytes: Uint8Array,
    options?: Partial<BinaryReadOptions>,
  ): RecordRef {
    return new RecordRef().fromBinary(bytes, options)
  }

  static fromJson(
    jsonValue: JsonValue,
    options?: Partial<JsonReadOptions>,
  ): RecordRef {
    return new RecordRef().fromJson(jsonValue, options)
  }

  static fromJsonString(
    jsonString: string,
    options?: Partial<JsonReadOptions>,
  ): RecordRef {
    return new RecordRef().fromJsonString(jsonString, options)
  }

  static equals(
    a: RecordRef | PlainMessage<RecordRef> | undefined,
    b: RecordRef | PlainMessage<RecordRef> | undefined,
  ): boolean {
    return proto3.util.equals(RecordRef, a, b)
  }
}

/**
 * @generated from message sokaa.GetLikesByActorAndSubjectsRequest
 */
export class GetLikesByActorAndSubjectsRequest extends Message<GetLikesByActorAndSubjectsRequest> {
  /**
   * @generated from field: string actor_did = 1;
   */
  actorDid = ''

  /**
   * @generated from field: repeated sokaa.RecordRef refs = 2;
   */
  refs: RecordRef[] = []

  constructor(data?: PartialMessage<GetLikesByActorAndSubjectsRequest>) {
    super()
    proto3.util.initPartial(data, this)
  }

  static readonly runtime: typeof proto3 = proto3
  static readonly typeName = 'sokaa.GetLikesByActorAndSubjectsRequest'
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: 'actor_did', kind: 'scalar', T: 9 /* ScalarType.STRING */ },
    { no: 2, name: 'refs', kind: 'message', T: RecordRef, repeated: true },
  ])

  static fromBinary(
    bytes: Uint8Array,
    options?: Partial<BinaryReadOptions>,
  ): GetLikesByActorAndSubjectsRequest {
    return new GetLikesByActorAndSubjectsRequest().fromBinary(bytes, options)
  }

  static fromJson(
    jsonValue: JsonValue,
    options?: Partial<JsonReadOptions>,
  ): GetLikesByActorAndSubjectsRequest {
    return new GetLikesByActorAndSubjectsRequest().fromJson(jsonValue, options)
  }

  static fromJsonString(
    jsonString: string,
    options?: Partial<JsonReadOptions>,
  ): GetLikesByActorAndSubjectsRequest {
    return new GetLikesByActorAndSubjectsRequest().fromJsonString(
      jsonString,
      options,
    )
  }

  static equals(
    a:
      | GetLikesByActorAndSubjectsRequest
      | PlainMessage<GetLikesByActorAndSubjectsRequest>
      | undefined,
    b:
      | GetLikesByActorAndSubjectsRequest
      | PlainMessage<GetLikesByActorAndSubjectsRequest>
      | undefined,
  ): boolean {
    return proto3.util.equals(GetLikesByActorAndSubjectsRequest, a, b)
  }
}

/**
 * @generated from message sokaa.GetLikesByActorAndSubjectsResponse
 */
export class GetLikesByActorAndSubjectsResponse extends Message<GetLikesByActorAndSubjectsResponse> {
  /**
   * @generated from field: repeated string uris = 1;
   */
  uris: string[] = []

  constructor(data?: PartialMessage<GetLikesByActorAndSubjectsResponse>) {
    super()
    proto3.util.initPartial(data, this)
  }

  static readonly runtime: typeof proto3 = proto3
  static readonly typeName = 'sokaa.GetLikesByActorAndSubjectsResponse'
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    {
      no: 1,
      name: 'uris',
      kind: 'scalar',
      T: 9 /* ScalarType.STRING */,
      repeated: true,
    },
  ])

  static fromBinary(
    bytes: Uint8Array,
    options?: Partial<BinaryReadOptions>,
  ): GetLikesByActorAndSubjectsResponse {
    return new GetLikesByActorAndSubjectsResponse().fromBinary(bytes, options)
  }

  static fromJson(
    jsonValue: JsonValue,
    options?: Partial<JsonReadOptions>,
  ): GetLikesByActorAndSubjectsResponse {
    return new GetLikesByActorAndSubjectsResponse().fromJson(jsonValue, options)
  }

  static fromJsonString(
    jsonString: string,
    options?: Partial<JsonReadOptions>,
  ): GetLikesByActorAndSubjectsResponse {
    return new GetLikesByActorAndSubjectsResponse().fromJsonString(
      jsonString,
      options,
    )
  }

  static equals(
    a:
      | GetLikesByActorAndSubjectsResponse
      | PlainMessage<GetLikesByActorAndSubjectsResponse>
      | undefined,
    b:
      | GetLikesByActorAndSubjectsResponse
      | PlainMessage<GetLikesByActorAndSubjectsResponse>
      | undefined,
  ): boolean {
    return proto3.util.equals(GetLikesByActorAndSubjectsResponse, a, b)
  }
}

/**
 * @generated from message sokaa.GetActorFollowsActorsRequest
 */
export class GetActorFollowsActorsRequest extends Message<GetActorFollowsActorsRequest> {
  /**
   * @generated from field: string actor_did = 1;
   */
  actorDid = ''

  /**
   * @generated from field: repeated string target_dids = 2;
   */
  targetDids: string[] = []

  constructor(data?: PartialMessage<GetActorFollowsActorsRequest>) {
    super()
    proto3.util.initPartial(data, this)
  }

  static readonly runtime: typeof proto3 = proto3
  static readonly typeName = 'sokaa.GetActorFollowsActorsRequest'
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: 'actor_did', kind: 'scalar', T: 9 /* ScalarType.STRING */ },
    {
      no: 2,
      name: 'target_dids',
      kind: 'scalar',
      T: 9 /* ScalarType.STRING */,
      repeated: true,
    },
  ])

  static fromBinary(
    bytes: Uint8Array,
    options?: Partial<BinaryReadOptions>,
  ): GetActorFollowsActorsRequest {
    return new GetActorFollowsActorsRequest().fromBinary(bytes, options)
  }

  static fromJson(
    jsonValue: JsonValue,
    options?: Partial<JsonReadOptions>,
  ): GetActorFollowsActorsRequest {
    return new GetActorFollowsActorsRequest().fromJson(jsonValue, options)
  }

  static fromJsonString(
    jsonString: string,
    options?: Partial<JsonReadOptions>,
  ): GetActorFollowsActorsRequest {
    return new GetActorFollowsActorsRequest().fromJsonString(
      jsonString,
      options,
    )
  }

  static equals(
    a:
      | GetActorFollowsActorsRequest
      | PlainMessage<GetActorFollowsActorsRequest>
      | undefined,
    b:
      | GetActorFollowsActorsRequest
      | PlainMessage<GetActorFollowsActorsRequest>
      | undefined,
  ): boolean {
    return proto3.util.equals(GetActorFollowsActorsRequest, a, b)
  }
}

/**
 * @generated from message sokaa.GetActorFollowsActorsResponse
 */
export class GetActorFollowsActorsResponse extends Message<GetActorFollowsActorsResponse> {
  /**
   * @generated from field: repeated string uris = 1;
   */
  uris: string[] = []

  constructor(data?: PartialMessage<GetActorFollowsActorsResponse>) {
    super()
    proto3.util.initPartial(data, this)
  }

  static readonly runtime: typeof proto3 = proto3
  static readonly typeName = 'sokaa.GetActorFollowsActorsResponse'
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    {
      no: 1,
      name: 'uris',
      kind: 'scalar',
      T: 9 /* ScalarType.STRING */,
      repeated: true,
    },
  ])

  static fromBinary(
    bytes: Uint8Array,
    options?: Partial<BinaryReadOptions>,
  ): GetActorFollowsActorsResponse {
    return new GetActorFollowsActorsResponse().fromBinary(bytes, options)
  }

  static fromJson(
    jsonValue: JsonValue,
    options?: Partial<JsonReadOptions>,
  ): GetActorFollowsActorsResponse {
    return new GetActorFollowsActorsResponse().fromJson(jsonValue, options)
  }

  static fromJsonString(
    jsonString: string,
    options?: Partial<JsonReadOptions>,
  ): GetActorFollowsActorsResponse {
    return new GetActorFollowsActorsResponse().fromJsonString(
      jsonString,
      options,
    )
  }

  static equals(
    a:
      | GetActorFollowsActorsResponse
      | PlainMessage<GetActorFollowsActorsResponse>
      | undefined,
    b:
      | GetActorFollowsActorsResponse
      | PlainMessage<GetActorFollowsActorsResponse>
      | undefined,
  ): boolean {
    return proto3.util.equals(GetActorFollowsActorsResponse, a, b)
  }
}

/**
 * @generated from message sokaa.PingRequest
 */
export class PingRequest extends Message<PingRequest> {
  constructor(data?: PartialMessage<PingRequest>) {
    super()
    proto3.util.initPartial(data, this)
  }

  static readonly runtime: typeof proto3 = proto3
  static readonly typeName = 'sokaa.PingRequest'
  static readonly fields: FieldList = proto3.util.newFieldList(() => [])

  static fromBinary(
    bytes: Uint8Array,
    options?: Partial<BinaryReadOptions>,
  ): PingRequest {
    return new PingRequest().fromBinary(bytes, options)
  }

  static fromJson(
    jsonValue: JsonValue,
    options?: Partial<JsonReadOptions>,
  ): PingRequest {
    return new PingRequest().fromJson(jsonValue, options)
  }

  static fromJsonString(
    jsonString: string,
    options?: Partial<JsonReadOptions>,
  ): PingRequest {
    return new PingRequest().fromJsonString(jsonString, options)
  }

  static equals(
    a: PingRequest | PlainMessage<PingRequest> | undefined,
    b: PingRequest | PlainMessage<PingRequest> | undefined,
  ): boolean {
    return proto3.util.equals(PingRequest, a, b)
  }
}

/**
 * @generated from message sokaa.PingResponse
 */
export class PingResponse extends Message<PingResponse> {
  constructor(data?: PartialMessage<PingResponse>) {
    super()
    proto3.util.initPartial(data, this)
  }

  static readonly runtime: typeof proto3 = proto3
  static readonly typeName = 'sokaa.PingResponse'
  static readonly fields: FieldList = proto3.util.newFieldList(() => [])

  static fromBinary(
    bytes: Uint8Array,
    options?: Partial<BinaryReadOptions>,
  ): PingResponse {
    return new PingResponse().fromBinary(bytes, options)
  }

  static fromJson(
    jsonValue: JsonValue,
    options?: Partial<JsonReadOptions>,
  ): PingResponse {
    return new PingResponse().fromJson(jsonValue, options)
  }

  static fromJsonString(
    jsonString: string,
    options?: Partial<JsonReadOptions>,
  ): PingResponse {
    return new PingResponse().fromJsonString(jsonString, options)
  }

  static equals(
    a: PingResponse | PlainMessage<PingResponse> | undefined,
    b: PingResponse | PlainMessage<PingResponse> | undefined,
  ): boolean {
    return proto3.util.equals(PingResponse, a, b)
  }
}
