// @generated by protoc-gen-connect-es v1.3.0 with parameter "target=ts,import_extension="
// @generated from file sokaa.proto (package sokaa, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import {
  GetActorFollowsActorsRequest,
  GetActorFollowsActorsResponse,
  GetActorsRequest,
  GetActorsResponse,
  GetAuthorFeedRequest,
  GetAuthorFeedResponse,
  GetLikesByActorAndSubjectsRequest,
  GetLikesByActorAndSubjectsResponse,
  GetPostsRequest,
  GetPostsResponse,
  GetRecentFeedRequest,
  GetRecentFeedResponse,
  GetTimelineRequest,
  GetTimelineResponse,
  PingRequest,
  PingResponse,
  SearchActorsRequest,
  SearchActorsResponse,
} from './sokaa_pb'
import { MethodKind } from '@bufbuild/protobuf'

/**
 * @generated from service sokaa.Service
 */
export const Service = {
  typeName: 'sokaa.Service',
  methods: {
    /**
     * @generated from rpc sokaa.Service.Ping
     */
    ping: {
      name: 'Ping',
      I: PingRequest,
      O: PingResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc sokaa.Service.GetTimeline
     */
    getTimeline: {
      name: 'GetTimeline',
      I: GetTimelineRequest,
      O: GetTimelineResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc sokaa.Service.GetAuthorFeed
     */
    getAuthorFeed: {
      name: 'GetAuthorFeed',
      I: GetAuthorFeedRequest,
      O: GetAuthorFeedResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc sokaa.Service.GetRecentFeed
     */
    getRecentFeed: {
      name: 'GetRecentFeed',
      I: GetRecentFeedRequest,
      O: GetRecentFeedResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc sokaa.Service.SearchActors
     */
    searchActors: {
      name: 'SearchActors',
      I: SearchActorsRequest,
      O: SearchActorsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc sokaa.Service.GetActors
     */
    getActors: {
      name: 'GetActors',
      I: GetActorsRequest,
      O: GetActorsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc sokaa.Service.GetPosts
     */
    getPosts: {
      name: 'GetPosts',
      I: GetPostsRequest,
      O: GetPostsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc sokaa.Service.GetLikesByActorAndSubjects
     */
    getLikesByActorAndSubjects: {
      name: 'GetLikesByActorAndSubjects',
      I: GetLikesByActorAndSubjectsRequest,
      O: GetLikesByActorAndSubjectsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc sokaa.Service.GetActorFollowsActors
     */
    getActorFollowsActors: {
      name: 'GetActorFollowsActors',
      I: GetActorFollowsActorsRequest,
      O: GetActorFollowsActorsResponse,
      kind: MethodKind.Unary,
    },
  },
} as const
