// Root Error class
export { OAuthError } from './errors/oauth-error.js'

export * from './errors/access-denied-error.js'
export * from './errors/account-selection-required-error.js'
export * from './errors/authorization-error.js'
export * from './errors/consent-required-error.js'
export * from './errors/handle-unavailable-error.js'
export * from './errors/invalid-authorization-details-error.js'
export * from './errors/invalid-client-error.js'
export * from './errors/invalid-client-id-error.js'
export * from './errors/invalid-client-metadata-error.js'
export * from './errors/invalid-dpop-key-binding-error.js'
export * from './errors/invalid-dpop-proof-error.js'
export * from './errors/invalid-grant-error.js'
export * from './errors/invalid-invite-code-error.js'
export * from './errors/invalid-redirect-uri-error.js'
export * from './errors/invalid-request-error.js'
export * from './errors/invalid-scope-error.js'
export * from './errors/invalid-token-error.js'
export * from './errors/login-required-error.js'
export * from './errors/second-authentication-factor-required-error.js'
export * from './errors/unauthorized-client-error.js'
export * from './errors/use-dpop-nonce-error.js'
export * from './errors/www-authenticate-error.js'
