// Allows typescript to properly type import of the files.json manifest file
// generated by rollup-plugin-bundle-manifest, even when it is not present at
// build time (e.g. during typecheck).
declare module '*/files.json' {
  import type { Manifest } from '@atproto-labs/rollup-plugin-bundle-manifest'
  declare const manifest: Manifest
  export default manifest
}
