// Allows TypeScript to properly type, during build, import of the files.json
// manifest file generated by rollup-plugin-bundle-manifest, even when it is not
// present.
declare module '*/files.json' {
  import type { Manifest } from '@atproto-labs/rollup-plugin-bundle-manifest'
  declare const manifest: Manifest
  export default manifest
}
