import { SeedClient } from './client'

export default async (sc: SeedClient) => {
  // @TODO when these are run in parallel, seem to get an intermittent
  // "TypeError: fetch failed" while running the tests.
  for (const { username, displayName } of users) {
    await sc.createAccount(username, {
      username: username,
      password: 'password',
      email: `${username}@bsky.app`,
    })
    if (displayName !== null) {
      await sc.createProfile(sc.dids[username], displayName, '')
    }
  }
  return sc
}

const users = [
  { username: 'silas77.test', displayName: 'Tanya Denesik' },
  { username: 'nicolas_krajcik10.test', displayName: null },
  { username: 'lennie-strosin.test', displayName: null },
  { username: 'aliya-hodkiewicz.test', displayName: 'Carlton Abernathy IV' },
  { username: 'jeffrey-sawayn87.test', displayName: 'Patrick Sawayn' },
  { username: 'kaycee66.test', displayName: null },
  { username: 'adrienne49.test', displayName: 'Kim Streich' },
  { username: 'magnus53.test', displayName: 'Sally Funk' },
  { username: 'charles_spencer.test', displayName: null },
  { username: 'elta48.test', displayName: 'Dr. Lowell DuBuque' },
  { username: 'tressa_senger.test', displayName: null },
  { username: 'marietta-zboncak.test', displayName: null },
  { username: 'alexander_hickle.test', displayName: 'Winifred Harber' },
  { username: 'rodger-maggio24.test', displayName: 'Yolanda VonRueden' },
  { username: 'janiya48.test', displayName: 'Miss Terrell Ziemann' },
  { username: 'cayla_marquardt39.test', displayName: 'Rachel Kshlerin' },
  { username: 'jonathan_green.test', displayName: 'Erica Mertz' },
  { username: 'brycen_smith.test', displayName: null },
  { username: 'leonel-koch43.test', displayName: 'Karl Bosco IV' },
  { username: 'fidel-rath.test', displayName: null },
  { username: 'raleigh_metz.test', displayName: null },
  { username: 'kim41.test', displayName: null },
  { username: 'roderick-dibbert.test', displayName: null },
  { username: 'alec_bergnaum.test', displayName: 'Cody Berge' },
  { username: 'sven70.test', displayName: null },
  { username: 'ola-oconnell.test', displayName: null },
  { username: 'chauncey_klein.test', displayName: 'Kelvin Klein' },
  { username: 'ariel_krajcik.test', displayName: null },
  { username: 'murphy35.test', displayName: 'Mrs. Clifford Mertz' },
  { username: 'joshuah-parker11.test', displayName: null },
  { username: 'dewitt-wunsch.test', displayName: null },
  { username: 'kelton-nitzsche43.test', displayName: null },
  { username: 'dock-mann91.test', displayName: 'Miss Danielle Weber' },
  { username: 'herman-gleichner95.test', displayName: 'Kelli Schinner III' },
  { username: 'gerda_marquardt.test', displayName: 'Myron Wolf' },
  { username: 'jamil_batz.test', displayName: null },
  { username: 'hilario84.test', displayName: null },
  { username: 'kayli_bode.test', displayName: 'Miss Floyd McClure' },
  { username: 'elouise28.test', displayName: 'Alberta Fay' },
  { username: 'leann49.test', displayName: null },
  { username: 'javon24.test', displayName: null },
  { username: 'polly-shanahan45.test', displayName: null },
  { username: 'rosamond38.test', displayName: 'Karl Goyette' },
  { username: 'fredrick-mueller.test', displayName: null },
  { username: 'reina_runte33.test', displayName: 'Pablo Schmidt' },
  { username: 'bianka33.test', displayName: null },
  { username: 'carlos6.test', displayName: null },
  { username: 'jermain-smith.test', displayName: 'Eileen Stroman' },
  { username: 'gina97.test', displayName: null },
  { username: 'kiera97.test', displayName: null },
  { username: 'savannah_botsford.test', displayName: 'Darnell Kuvalis' },
  { username: 'lilliana_waters.test', displayName: null },
  { username: 'hailey_stroman.test', displayName: 'Elsa Schaden' },
  { username: 'dortha_terry.test', displayName: 'Nicole Bradtke' },
  { username: 'hank-powlowski32.test', displayName: null },
  { username: 'ervin-daugherty.test', displayName: null },
  { username: 'nannie18.test', displayName: null },
  { username: 'gilberto-watsica65.test', displayName: 'Ms. Ida Wilderman' },
  { username: 'kara-zieme58.test', displayName: 'Andres Towne' },
  { username: 'crystal-boyle.test', displayName: null },
  { username: 'tobin63.test', displayName: 'Alex Johnson' },
  { username: 'isai-kunze72.test', displayName: 'Marion Dickinson' },
  { username: 'paris-swift.test', displayName: null },
  { username: 'nestor90.test', displayName: 'Travis Hoppe' },
  { username: 'aliyah_flatley12.test', displayName: 'Loren Krajcik' },
  { username: 'maiya42.test', displayName: null },
  { username: 'dovie33.test', displayName: null },
  { username: 'kendra_ledner80.test', displayName: 'Sergio Hane' },
  { username: 'greyson-tromp3.test', displayName: null },
  { username: 'precious_fay.test', displayName: null },
  { username: 'kiana_schmitt39.test', displayName: null },
  { username: 'rhianna_stamm29.test', displayName: null },
  { username: 'tiara_mohr.test', displayName: null },
  { username: 'eleazar-balistreri70.test', displayName: 'Gordon Weissnat' },
  { username: 'bettie-bogisich96.test', displayName: null },
  { username: 'lura-jacobi55.test', displayName: null },
  { username: 'santa_hermann78.test', displayName: 'Melissa Johnson' },
  { username: 'dylan61.test', displayName: null },
  { username: 'ryley_kerluke.test', displayName: 'Alexander Purdy' },
  { username: 'moises-bins8.test', displayName: null },
  { username: 'angelita-schaefer27.test', displayName: null },
  { username: 'natasha83.test', displayName: 'Dean Romaguera' },
  { username: 'sydni48.test', displayName: null },
  { username: 'darrion91.test', displayName: 'Jeanette Weimann' },
  { username: 'reynold-ortiz.test', displayName: null },
  { username: 'hassie-schuppe.test', displayName: 'Rita Zieme' },
  { username: 'clark_stehr8.test', displayName: 'Sammy Larkin' },
  { username: 'preston_harris.test', displayName: 'Ms. Bradford Thiel' },
  { username: 'benedict-schulist.test', displayName: 'Todd Stark' },
  { username: 'alden_wolff22.test', displayName: null },
  { username: 'joel-gulgowski.test', displayName: null },
  { username: 'joanie56.test', displayName: 'Ms. Darin Cole' },
  { username: 'israel_hermann0.test', displayName: 'Wilbur Schuster' },
  { username: 'tracy56.test', displayName: null },
  { username: 'kyle72.test', displayName: null },
  { username: 'gunnar_dare70.test', displayName: 'Mrs. Angelo Keeling' },
  { username: 'justus58.test', displayName: null },
  { username: 'brooke24.test', displayName: 'Clint Ward' },
  { username: 'angela-morissette.test', displayName: 'Jim Kertzmann' },
  { username: 'amy_bins.test', displayName: 'Angelina Hills' },
  { username: 'susanna81.test', displayName: null },
  { username: 'jailyn_hettinger50.test', displayName: 'Sheldon Ratke' },
  { username: 'wendell_hansen54.test', displayName: null },
  { username: 'jennyfer-spinka.test', displayName: 'Leticia Blick' },
  { username: 'alexandrea31.test', displayName: 'Leslie Von' },
  { username: 'hazle_davis.test', displayName: 'Ella Farrell' },
  { username: 'alta6.test', displayName: null },
  { username: 'sherwood4.test', displayName: 'Dr. Hattie Nienow I' },
  { username: 'marilie24.test', displayName: 'Gene Howell' },
  { username: 'jimmie_feeney82.test', displayName: null },
  { username: 'trisha_ohara.test', displayName: null },
  { username: 'jake_schuster33.test', displayName: 'Raymond Price' },
  { username: 'shane_torphy52.test', displayName: 'Sadie Carter' },
  { username: 'nakia_kuphal8.test', displayName: null },
  { username: 'lea_trantow.test', displayName: null },
  { username: 'joel62.test', displayName: 'Veronica Nitzsche' },
  { username: 'roosevelt33.test', displayName: 'Jay Moen' },
  { username: 'talon_okeefe85.test', displayName: null },
  { username: 'herman_dare.test', displayName: 'Eric White' },
  { username: 'flavio_fay.test', displayName: 'John Lindgren' },
  { username: 'elyse-prosacco.test', displayName: null },
  { username: 'jessyca-wiegand23.test', displayName: 'Debra Lockman' },
  { username: 'ara_spencer41.test', displayName: null },
  { username: 'frederic_fadel.test', displayName: null },
  { username: 'zora_gerlach.test', displayName: 'Noel Hansen' },
  { username: 'spencer4.test', displayName: 'Marjorie Gorczany' },
  { username: 'gage_wilkinson33.test', displayName: 'Preston Schoen V' },
  { username: 'kiley_runolfsson1.test', displayName: null },
  { username: 'ramona80.test', displayName: 'Sylvia Dietrich' },
  { username: 'rashad97.test', displayName: null },
  { username: 'kylie76.test', displayName: 'Josefina Pfeffer' },
  { username: 'alisha-zieme.test', displayName: null },
  { username: 'claud79.test', displayName: null },
  { username: 'jairo-kuvalis.test', displayName: 'Derrick Jacobson' },
  { username: 'delfina_emard.test', displayName: null },
  { username: 'waino-gutmann20.test', displayName: 'Wesley Kemmer' },
  { username: 'arvid_hermiston49.test', displayName: 'Vernon Towne PhD' },
  { username: 'hans79.test', displayName: 'Rex Hartmann' },
  { username: 'karlee-greenholt40.test', displayName: null },
  { username: 'nels-cummings.test', displayName: null },
  { username: 'andrew_maggio.test', displayName: null },
  { username: 'stephany75.test', displayName: null },
  { username: 'alba-lueilwitz.test', displayName: null },
  { username: 'fermin47.test', displayName: null },
  { username: 'milo_quitzon3.test', displayName: null },
  { username: 'eudora_dietrich4.test', displayName: 'Carol Littel' },
  { username: 'uriel-witting12.test', displayName: 'Sophia Schmidt' },
  { username: 'reuben-stracke48.test', displayName: 'Darrell Walker MD' },
  { username: 'letitia-sawayn11.test', displayName: 'Mrs. Sophie Reilly' },
  { username: 'macy_schaden.test', displayName: 'Lindsey Klein' },
  { username: 'imelda61.test', displayName: 'Shannon Beier' },
  { username: 'oswald_bailey.test', displayName: 'Angel Mann' },
  { username: 'pattie-fisher34.test', displayName: null },
  { username: 'loyce95.test', displayName: 'Claude Tromp' },
  { username: 'melyna_zboncak.test', displayName: null },
  { username: 'rowan_parisian.test', displayName: 'Mr. Veronica Feeney' },
  { username: 'lois-blanda20.test', displayName: 'Todd Rolfson' },
  { username: 'turner_balistreri76.test', displayName: null },
  { username: 'dee_hoppe65.test', displayName: null },
  { username: 'nikko_rosenbaum60.test', displayName: 'Joann Gutmann' },
  { username: 'cornell-romaguera53.test', displayName: null },
  { username: 'zack3.test', displayName: null },
  { username: 'fredrick41.test', displayName: 'Julius Kreiger' },
  { username: 'elwyn62.test', displayName: null },
  { username: 'isaias-hirthe37.test', displayName: 'Louis Cremin' },
  { username: 'ronaldo36.test', displayName: null },
  { username: 'jesse34.test', displayName: 'Bridget Schulist' },
  { username: 'darrel-mills17.test', displayName: null },
  { username: 'euna_mayert92.test', displayName: 'Grant Lang II' },
  { username: 'terrell92.test', displayName: null },
  { username: 'alyson_bogisich.test', displayName: 'Dana MacGyver' },
  { username: 'nicolas65.test', displayName: null },
  { username: 'bernita8.test', displayName: null },
  { username: 'gunner23.test', displayName: 'Maggie DuBuque' },
  { username: 'phoebe80.test', displayName: null },
  { username: 'cory-cruickshank.test', displayName: null },
  { username: 'conor_price.test', displayName: 'Ralph Daugherty III' },
  { username: 'rae91.test', displayName: null },
  { username: 'abigale-cronin.test', displayName: null },
  { username: 'aileen-reilly90.test', displayName: 'Charles Stanton' },
  { username: 'adrianna-hansen6.test', displayName: 'Elbert Langworth IV' },
  { username: 'pierre54.test', displayName: null },
  { username: 'jaida_stark62.test', displayName: 'Justin Stoltenberg MD' },
  { username: 'wade-witting.test', displayName: null },
  { username: 'yvonne_predovic5.test', displayName: 'Gregory Hamill' },
  { username: 'spencer-dubuque.test', displayName: null },
  { username: 'randi44.test', displayName: null },
  { username: 'maye_grimes.test', displayName: null },
  { username: 'margarette-effertz.test', displayName: null },
  { username: 'aimee98.test', displayName: null },
  { username: 'jaren_veum0.test', displayName: 'Dr. Omar Wolff' },
  { username: 'ariel_abbott54.test', displayName: 'Emanuel Powlowski' },
  { username: 'mercedes23.test', displayName: null },
  { username: 'jarrett_orn.test', displayName: null },
  { username: 'damion88.test', displayName: null },
  { username: 'nayeli_koss73.test', displayName: 'Johnny Lang' },
  { username: 'cara-wiegand69.test', displayName: null },
  { username: 'gideon_ohara51.test', displayName: null },
  { username: 'carolina_mcdermott77.test', displayName: 'Latoya Windler' },
  { username: 'danyka90.test', displayName: 'Hope Kub' },
]
