name: Publish

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: write
  pull-requests: write

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    name: Publish
    if: github.repository == 'bluesky-social/atproto'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v6
        with:
          cache: pnpm
          node-version-file: '.nvmrc'
          registry-url: 'https://registry.npmjs.org'
      # Temporary workaround for an issue with Node.js v22
      # https://github.com/npm/cli/issues/9151
      # https://github.com/npm/cli/pull/9152
      - run: npm install --global npm@11.11.1
      - run: npm install --global npm@latest
      - run: pnpm install --frozen-lockfile
        env:
          PUPPETEER_SKIP_DOWNLOAD: true
      # Removing generated code to ensure that the "prebuild" step is run and
      # generates fresh code. This is needed because "ozone" and "api" won't run
      # "codegen" as "prebuild" if the codegen code already exists (because it
      # takes a long time to run). Once they are migrated to use "@atproto/lex"
      # (and have a "prebuild" step), we can remove the explicit "rm" command
      # here.
      - run: rm -r packages/api/src/client packages/ozone/src/lexicon
      - name: Publish
        uses: changesets/action@v1
        id: changesets
        with:
          publish: pnpm run publish:ci
          version: pnpm run version-packages
          commit: 'Version packages'
          title: 'Version packages'
