name: Publish

on:
  push:
    branches:
      - main
      - permissioned-data-alpha

concurrency:
  group: publish-${{ github.ref }}
  cancel-in-progress: false

permissions:
  id-token: write
  contents: write
  pull-requests: write

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    name: Publish
    if: github.repository == 'bluesky-social/atproto'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: pnpm/action-setup@v6
      - uses: actions/setup-node@v7
        with:
          cache: pnpm
          node-version-file: '.nvmrc'
          registry-url: 'https://registry.npmjs.org'
      - run: pnpm install --frozen-lockfile
        env:
          PUPPETEER_SKIP_DOWNLOAD: true
      - name: Publish stable releases
        if: github.ref_name == 'main'
        uses: changesets/action@v1
        id: changesets
        with:
          publish: pnpm run publish:ci
          version: pnpm run version-packages
          commit: 'Version packages'
          title: 'Version packages'
      - name: Publish alpha snapshots
        if: github.ref_name == 'permissioned-data-alpha'
        env:
          npm_config_tag: alpha
        run: |
          pnpm changeset version --snapshot alpha
          pnpm build
          pnpm --filter @atproto/crypto publish --tag alpha --provenance --no-git-checks --access
