name: Publish

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: write
  pull-requests: write

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    name: Publish
    if: github.repository == 'bluesky-social/atproto'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          cache: false
      - uses: actions/setup-node@v6
        with:
          node-version-file: '.nvmrc'
          registry-url: 'https://registry.npmjs.org'
          # ⚠️ Do not use cache on purpose during publish to avoid any potential
          # cache poisoning issues. We want to make sure we always download the
          # dependencies from NPM.
          # cache: pnpm
          package-manager-cache: false
      # Temporary workaround for an issue with Node.js v22
      # https://github.com/npm/cli/issues/9151
      # https://github.com/npm/cli/pull/9152
      - run: npm install --global npm@11.11.1
      - run: npm install --global npm@latest
      - run: pnpm install --frozen-lockfile
        env:
          PUPPETEER_SKIP_DOWNLOAD: true
      - name: Publish
        uses: changesets/action@v1
        id: changesets
        with:
          publish: pnpm run publish:ci
          version: pnpm run version-packages
          commit: 'Version packages'
          title: 'Version packages'
